################################################################
#
#
# Pipeline pipeline_cat_fastq.py configuration file for sphinxreport
#
# This pipeline.ini file lists some configuration options that you might 
# want a user to set automatically.
#
# Add pipeline specific options into separate sections
#
################################################################
## general options


# Project name
projectname: CGATProject

# Copyright statement
copyright: CGAT (2010-2014)

# The short X.Y version.
version: 0.1

# The full version, including alpha/beta/rc tags.
release: 0.1

# location of Illumina format fastq files
inlocation: '/ifs/research-groups/botnar/proj034/backup/comp11/'

# location for output fastq files
outlocation: '/ifs/research-groups/botnar/proj034/analyses/comp11/data.dir/'

# merge pattern - defaults are for illumina to cgat
merge:
    pattern_input: '(\S+)_R(\d+)\S+'

