################################################################
#
#
# Pipeline pipeline_cat_fastq.py configuration file for sphinxreport
#
# This pipeline.ini file lists some configuration options that you might 
# want a user to set automatically.
#
# Add pipeline specific options into separate sections
#
################################################################
## general options


# Project name
projectname: CGATProject

# Copyright statement
copyright: CGAT (2010-2014)

# The short X.Y version.
version: 0.1

# The full version, including alpha/beta/rc tags.
release: 0.1

chromhmm:
    segment_bed: "/ifs/research-groups/botnar/proj003/analyses/Adam_analysis/Chromhmm/output.dir/JMJD3_J4_10_segments.bed"

gat:
    contig: "/ifs/mirror/annotations/hg19_ensembl75_hierarchical/assembly.dir/contigs.bed.gz"

    annotation_bed: "/ifs/research-groups/botnar/proj003/analyses/Adam_analysis/Chromhmm/output.dir/merged_annotation.bed.gz"

geneexpression:
    present: 1

    coding_gene: /ifs/mirror/annotations/hg19_ensembl75_hierarchical/geneset.dir/coding_gene_region.bed.gz

    coding_gene_gtf: /ifs/mirror/annotations/hg19_ensembl75_hierarchical/ensembl.dir/geneset_coding_exons.gtf.gz
    tss: /ifs/mirror/annotations/hg19_ensembl75_hierarchical/geneset.dir/coding_gene_tss.bed.gz
    tts: /ifs/mirror/annotations/hg19_ensembl75_hierarchical/geneset.dir/coding_gene_tts.bed.gz
    gene_lists: [/ifs/research-groups/botnar/proj003/analyses/Adam_analysis/Chromhmm/output.dir/downregulated.csv,/ifs/research-groups/botnar/proj003/analyses/Adam_analysis/Chromhmm/output.dir/upregulated.csv]

homer:
    genome: hg19