################################################################
#
# Pipeline pipeline_quantchip.py configuration file
#
# This pipeline.yml file lists some configuration options that you
# need to set before running the pipeline 
#
################################################################

# Location of the cribbslab directory
cribbslab: '/ifs/projects/adam/cribbslab/'

# Project name
projectname: proj001

# Copyright statement
copyright: Cribbs Group, Botnar Research Centre (2018)


########################################################
# the genome to use (UCSC convention)
########################################################

genome: hg19


##########################################################
# specifying the regex to pick up the spike in reads
##########################################################

quant:
    regex: sf9


###########################################################
# Options for running homers annotatePeaks
###########################################################

homer:
    options: '-size 4000 -hist 50'


###########################################################
# Options for mergeing bigwigs based on regex
###########################################################

merge_pattern_input: i\S+-(\S+)-\S+-(\S+)_\S+

merge_pattern_output: \1-\2