"""===========================
Pipeline sclong
===========================

Overview
========

This pipeline performs analysis of 10x Genomics single-cell long-read RNA-seq
data from nuclei sequencing (ONT). The workflow handles both full-length and
spliced reads with quantification at both gene and transcript levels.

Supports both 10x 5' and 3' chemistries.

Key features:
- Cell barcode and UMI extraction using BLAZE (supports 5' and 3' kits)
- Splice-aware alignment with minimap2
- Transcript discovery and quantification using FLAMES (from FASTQ)
- Transcript quantification using IsoQuant (from tagged BAM, concurrent with FLAMES):
  spliced transcript-level and unspliced gene-level AnnData matrices,
  per-barcode splicing-proportion QC surfaced in MultiQC
- Combined gene-level and transcript-level count matrices (spliced + unspliced)
- Separate spliced/unspliced matrices for RNA velocity analysis
- Handling of both spliced and unspliced reads (important for nuclei)

Usage
=====

To run locally:

    python pipeline_sclong.py make full --local -j 8

Configuration
-------------

The pipeline requires a configured :file:`pipeline.yml` file.

Default configuration files can be generated by executing:

   python <srcdir>/pipeline_sclong.py config

Important: Set the correct kit type in pipeline.yml:
- kit: 3v3  # For 10x 3' v3 chemistry
- kit: 5v2  # For 10x 5' v2 chemistry

Input files
-----------

* Fastq files from 10x ONT single-cell sequencing (*.fastq.gz or *.fastq)
* Reference genome (fasta)
* Annotation file (GTF)
* 10x barcode whitelist file (3M-february-2018.txt for v3)

Requirements
------------

* BLAZE - for cell barcode assignment (handles 5' and 3' kits)
* minimap2 - for splice-aware alignment
* samtools - for BAM processing
* FLAMES (R package) - for single-cell isoform analysis
* IsoQuant - for single-cell transcript quantification from tagged BAM
* featureCounts - for gene-level counting

Pipeline output
===============

* Cell barcode assignments (blaze/)
* Aligned BAM files with cell barcode tags (tagged/)
* BAM subsets for true cells only (tagged_cells/)
* IsoQuant SC outputs: transcript/gene count matrices (isoquant/)
* Spliced transcript AnnData and unspliced gene AnnData (splice_matrices/)
* Per-barcode splicing-proportion QC, MultiQC custom content (qc_splice/)
* Combined gene-level count matrix - spliced + unspliced (combined_counts/)
* Transcript-level count matrix (flames/)
* Separate spliced/unspliced matrices for velocity (velocity/)
* Novel transcript GTF (flames/)
* QC reports (multiqc/)

Output count matrices include BOTH spliced and unspliced reads to capture
the full transcriptome from nuclei, where unspliced pre-mRNA is abundant.

Processing steps
================

1. BLAZE barcode assignment from long reads (kit-aware: 5' or 3')
2. Minimap2 splice-aware alignment
3. BAM tagging with cell barcodes and UMIs
4a. FLAMES transcript discovery and quantification (from FASTQ)
4b. IsoQuant transcript quantification (from tagged BAM, concurrent with 4a):
    subset BAM to true cells, quantify with --barcoded_bam, derive
    spliced transcript and unspliced gene AnnData matrices, splice QC
5. Combined gene-level counting (spliced + unspliced)
6. Separate velocity matrices (spliced/unspliced for scVelo)
7. QC and MultiQC reporting (including splice-proportion outlier table)

Code
====

"""

import sys
import os
from ruffus import *
import cgatcore.pipeline as P
import cgatcore.experiment as E

# load options from the config file
PARAMS = P.get_parameters(
    ["%s/pipeline.yml" % os.path.splitext(__file__)[0],
     "../pipeline.yml",
     "pipeline.yml"])


SEQUENCESUFFIXES = ("*.fastq.gz",
                    "*.fastq",
                    "*.fq.gz",
                    "*.fq")

SEQUENCEFILES = tuple([os.path.join('.', suffix_name)
                       for suffix_name in SEQUENCESUFFIXES])

SEQUENCEFILES_REGEX = regex(
    r".*/(\S+)\.(fastq\.gz|fastq|fq\.gz|fq)")


# -----------------------------------------------
# BLAZE: Cell barcode assignment (10x 5' and 3' kits)
# -----------------------------------------------

@follows(mkdir("blaze"))
@transform(SEQUENCEFILES,
           SEQUENCEFILES_REGEX,
           r"blaze/\1_putative_bc.csv")
def run_blaze(infile, outfile):
    """
    Run BLAZE to identify cell barcodes from 10x long reads.
    BLAZE uses a probabilistic model to assign 10x-style barcodes
    to long reads based on the barcode whitelist.

    Supports both 10x 5' and 3' chemistries:
    - 3' kit (3v3): barcode + UMI at 3' end near poly-A tail
    - 5' kit (5v2): barcode + UMI at 5' end of read

    Parameters from pipeline.yml:
        blaze_kit: 10x kit type (3v3, 5v2, etc.)
        blaze_whitelist: path to 10x barcode whitelist
        blaze_expect_cells: expected number of cells
    """

    outdir = os.path.dirname(outfile)
    basename = os.path.basename(infile).split('.')[0]

    job_threads = PARAMS.get("blaze_threads", 8)
    job_memory = PARAMS.get("blaze_memory", "16G")

    kit_type = PARAMS.get("blaze_kit", "3v3")  # Default to 3' v3 chemistry
    expect_cells = PARAMS.get("blaze_expect_cells", 5000)
    blaze_options = PARAMS.get("blaze_options", "")

    # BLAZE bundles the standard 10x whitelists and selects one based on the
    # kit version, so a whitelist only needs to be supplied for custom
    # (non-10x) barcodes via --full-bc-whitelist.
    whitelist = PARAMS.get("blaze_whitelist", "")
    if whitelist and os.path.exists(whitelist):
        whitelist_option = "--full-bc-whitelist %s" % whitelist
    else:
        whitelist_option = ""

    statement = """
        blaze
        --10x-kit-version %(kit_type)s
        --expect-cells %(expect_cells)s
        --threads %(job_threads)s
        %(whitelist_option)s
        %(blaze_options)s
        --output-prefix %(outdir)s/%(basename)s_
        %(infile)s
    """

    P.run(statement)


# -----------------------------------------------
# Generate splice junction BED from GTF annotation
# -----------------------------------------------

@follows(mkdir("aligned"))
@transform(PARAMS.get("minimap2_gtf", PARAMS.get("featurecounts_gtf", "")),
           regex(r"(.*)"),
           r"aligned/junctions.bed")
def generate_junc_bed(infile, outfile):
    """
    Convert GTF annotation to a splice junction BED file using paftools.js.
    This improves minimap2 splice alignment accuracy by providing known
    splice sites, helping to better distinguish spliced from unspliced reads.
    """

    job_memory = PARAMS.get("minimap2_memory", "8G")

    if infile.endswith(".gz"):
        cat_cmd = "zcat"
    else:
        cat_cmd = "cat"

    statement = """
        %(cat_cmd)s %(infile)s
        | paftools.js gff2bed /dev/stdin
        > %(outfile)s
    """

    P.run(statement)


# -----------------------------------------------
# Alignment with minimap2 (splice-aware)
# -----------------------------------------------

@follows(generate_junc_bed)
@transform(SEQUENCEFILES,
           SEQUENCEFILES_REGEX,
           r"aligned/\1.bam")
def align_minimap2(infile, outfile):
    """
    Align reads using minimap2 with splice-aware settings.
    Uses settings optimized for single-cell long-read data.

    For nuclei data, -ax splice maps to the genome so both spliced
    and unspliced (intron-retaining) reads are captured. The --junc-bed
    file provides known splice sites to improve alignment accuracy.

    Parameters from pipeline.yml:
        genome_fasta: path to reference genome fasta
        minimap2_options: additional minimap2 options
        minimap2_gtf: GTF used to generate junction BED
    """

    job_threads = PARAMS.get("minimap2_threads", 16)
    job_memory = PARAMS.get("minimap2_memory", "8G")

    genome_fasta = PARAMS["genome_fasta"]
    minimap2_options = PARAMS.get("minimap2_options", "-ax splice -uf -k14")
    junc_bed = "aligned/junctions.bed"

    # Per-thread memory for samtools sort. The default (768M/thread) silently
    # scales with -@, so for large runs this bounds the sort buffer explicitly.
    sort_memory = PARAMS.get("minimap2_sort_memory", "1G")
    # Keep sort temp files next to the output (on the working disk) rather than
    # in a possibly-small /tmp, and give them a unique prefix per BAM.
    sort_tmp = outfile + ".sorttmp"
    # Capture minimap2's own stderr separately so that when it exits abnormally
    # (OOM-kill, crash, etc.) we keep its real error message instead of only
    # seeing samtools' downstream "truncated file" complaint about the broken pipe.
    minimap2_log = outfile + ".minimap2.log"

    # pipefail ensures a minimap2 failure (e.g. OOM-kill or a corrupt input
    # FASTQ) propagates as an error instead of being masked by samtools, which
    # would otherwise abort on the partial stream and leave a half-written BAM.
    statement = """
        set -o pipefail &&
        minimap2 %(minimap2_options)s
        --junc-bed %(junc_bed)s
        -t %(job_threads)s
        %(genome_fasta)s
        %(infile)s
        2> %(minimap2_log)s
        | samtools sort -@ %(job_threads)s -m %(sort_memory)s
        -T %(sort_tmp)s -O bam -o %(outfile)s -
        && samtools index %(outfile)s
    """

    P.run(statement)


# -----------------------------------------------
# Tag BAM with cell barcodes (10x compatible)
# -----------------------------------------------

@follows(mkdir("tagged"), run_blaze)
@transform(align_minimap2,
           regex(r"aligned/(\S+)\.bam"),
           r"tagged/\1.tagged.bam")
def tag_bam_with_barcodes(infile, outfile):
    """
    Add cell barcode (CB) and UMI (UB) tags to BAM file
    using BLAZE barcode assignments.
    
    Tags are added in 10x-compatible format:
    - CB:Z: cell barcode
    - UB:Z: UMI sequence
    """

    # Get corresponding BLAZE output
    basename = os.path.basename(infile).replace(".bam", "")
    blaze_bc = "blaze/{}_putative_bc.csv".format(basename)

    job_memory = PARAMS.get("tag_memory", "16G")

    R_SRC_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), "R"))

    statement = """
        Rscript %(R_SRC_PATH)s/tag_bam_barcodes.R
        --bam %(infile)s
        --barcodes %(blaze_bc)s
        --output %(outfile)s
        && samtools index %(outfile)s
    """

    P.run(statement)


# -----------------------------------------------
# Subset tagged BAM to true cells before IsoQuant
# -----------------------------------------------

@follows(mkdir("tagged_cells"))
@transform(tag_bam_with_barcodes,
           regex(r"tagged/(\S+)\.tagged\.bam"),
           r"tagged_cells/\1.cells.bam")
def subset_cells(infile, outfile):
    """
    Subset the tagged BAM to barcodes in the BLAZE cell whitelist.

    IsoQuant is run with --barcoded_bam, which quantifies every CB tag it
    finds. Restricting to true cells here keeps deduplication and
    quantification clean and avoids processing ambient/noise barcodes.

    The whitelist is resolved in order:
      1. isoquant_cell_whitelist from pipeline.yml (supports {sample}
         placeholder for per-sample lists).
      2. blaze/{sample}_whitelist.csv produced by run_blaze.
      3. If neither exists the tagged BAM is symlinked through unchanged
         so the task remains idempotent.

    Strand assumption: minimap2 is run with -uf, so only forward-strand
    alignments are produced. IsoQuant inherits this strand orientation when
    reading the BAM. Wrong-strand intronic reads would contaminate the
    unspliced matrix; this is guarded against by the upstream -uf flag.

    Note on barcode format: BLAZE whitelists carry bare barcodes (no GEM-well
    suffix). When isoquant.strip_barcode_suffix is enabled, IsoQuant strips
    the dash suffix from CB tags before matching -- ensure the whitelist
    format is consistent with this setting.
    """

    sample = os.path.basename(infile).replace(".tagged.bam", "")

    job_memory = PARAMS.get("isoquant_memory", "16G")

    # Resolve cell whitelist
    wl_param = PARAMS.get("isoquant_cell_whitelist", "")
    if wl_param:
        whitelist = wl_param.replace("{sample}", sample)
    else:
        whitelist = "blaze/{}_whitelist.csv".format(sample)

    if not os.path.exists(whitelist):
        # No whitelist available -- pass through with a symlink
        outbai = outfile + ".bai"
        inbai = infile + ".bai"
        statement = """
            ln -sf $(realpath %(infile)s) %(outfile)s
            && ln -sf $(realpath %(inbai)s) %(outbai)s
        """
        P.run(statement)
        return

    # Extract barcode column (first column, skip header lines starting with #)
    bc_list = outfile + ".bc_list.txt"

    # samtools view -D CB:<file> filters reads whose CB tag matches any
    # barcode in the file (one barcode per line, no header).
    # The BLAZE whitelist is CSV; take the first field, skip comment lines.
    statement = """
        grep -v '^#' %(whitelist)s
        | cut -d',' -f1
        | grep -v '^barcode' > %(bc_list)s
        && samtools view -h -b -D CB:%(bc_list)s %(infile)s
        | samtools sort -o %(outfile)s -
        && samtools index %(outfile)s
        && rm -f %(bc_list)s
    """

    P.run(statement)


# -----------------------------------------------
# IsoQuant: Transcript quantification (single-cell, from tagged BAM)
# -----------------------------------------------

@follows(mkdir("isoquant"))
@transform(subset_cells,
           regex(r"tagged_cells/(\S+)\.cells\.bam"),
           r"isoquant/\1/isoquant.sentinel")
def quantify_isoquant(infile, outfile):
    """
    Quantify transcripts and genes using IsoQuant in single-cell mode.

    IsoQuant reads cell barcodes and UMIs directly from the BAM tags set by
    BLAZE/tag_bam_barcodes.R (--barcoded_bam). UMI-based deduplication is
    performed natively by IsoQuant within each barcode x gene group.

    IsoQuant runs concurrently with FLAMES (which operates from FASTQ).
    These are independent quantification routes and produce complementary
    outputs: IsoQuant provides transcript-level spliced and gene-level
    unspliced matrices derived here; FLAMES provides novel isoform discovery.

    Strand: minimap2 upstream uses -uf (forward-strand only). IsoQuant
    inherits this orientation from the BAM. Intronic reads on the wrong
    strand would contaminate the unspliced matrix; the -uf flag prevents this.

    TODO: confirm that the installed IsoQuant version performs Levenshtein
    edit-distance UMI deduplication (expected ED3 for tenX_v3 mode). If
    exact-match-only dedup is used, ONT UMI error will inflate counts.
    The pre_collapse config key (isoquant.pre_collapse) is reserved for a
    future upstream correction step but is not implemented here.
    """

    sample = os.path.basename(os.path.dirname(outfile))
    outdir = os.path.dirname(outfile)

    job_threads = PARAMS.get("isoquant_threads", 8)
    job_memory = PARAMS.get("isoquant_memory", "64G")

    binary = PARAMS.get("isoquant_binary", "isoquant.py")
    mode = PARAMS.get("isoquant_mode", "tenX_v3")
    gtf = PARAMS.get("isoquant_gtf", PARAMS.get("flames_gtf",
                     PARAMS.get("featurecounts_gtf", "")))
    fasta = PARAMS.get("isoquant_fasta", PARAMS["genome_fasta"])
    barcode_tag = PARAMS.get("isoquant_barcode_tag", "CB")
    umi_tag = PARAMS.get("isoquant_umi_tag", "UB")
    strip_suffix = PARAMS.get("isoquant_strip_barcode_suffix", True)

    strip_opt = "--strip_barcode_suffix" if strip_suffix else ""

    statement = """
        %(binary)s
        --reference %(fasta)s
        --genedb %(gtf)s
        --complete_genedb
        --bam %(infile)s
        --data_type nanopore
        --mode %(mode)s
        --barcoded_bam
        --barcode_tag %(barcode_tag)s
        --umi_tag %(umi_tag)s
        %(strip_opt)s
        --count_exons
        --counts_format mtx
        -o %(outdir)s
        -p %(sample)s
        -t %(job_threads)s
        && touch %(outfile)s
    """

    P.run(statement)


# -----------------------------------------------
# FLAMES: Transcript discovery and quantification
# -----------------------------------------------

@follows(mkdir("flames"), run_blaze)
@transform(SEQUENCEFILES,
           SEQUENCEFILES_REGEX,
           r"flames/\1/flames_output.sentinel")
def run_flames(infile, outfile):
    """
    Run FLAMES for single-cell transcript discovery and quantification.

    FLAMES 2.x runs end-to-end from FASTQ (it performs its own barcode
    demultiplexing and minimap2 alignment internally - it does not accept
    pre-aligned BAMs). One FLAMES run is performed per input sample.

    FLAMES performs:
    - Cell barcode demultiplexing (flexiplex against the BLAZE whitelist if
      available, otherwise BLAZE using the expected cell number)
    - Splice-aware genome alignment
    - Novel isoform identification
    - Transcript- and gene-level quantification

    Parameters from pipeline.yml:
        flames_gtf: annotation GTF file
        flames_fasta: reference genome fasta
        flames_min_support_reads / flames_do_discovery
        blaze_expect_cells: expected number of cells
    """

    R_SRC_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), "R"))

    outdir = os.path.dirname(outfile)
    sample = os.path.basename(outdir)

    job_threads = PARAMS.get("flames_threads", 8)
    job_memory = PARAMS.get("flames_memory", "64G")

    min_support = PARAMS.get("flames_min_support_reads", 3)
    do_discovery = PARAMS.get("flames_do_discovery", True)
    expect_cells = PARAMS.get("blaze_expect_cells", 5000)

    # Reuse the BLAZE cell-barcode whitelist (if present) so FLAMES demultiplexes
    # against the already-identified barcodes instead of re-running BLAZE.
    whitelist = "blaze/{}_whitelist.csv".format(sample)
    barcodes_option = ""
    if os.path.exists(whitelist):
        barcodes_option = "--barcodes %s" % whitelist

    statement = """
        Rscript %(R_SRC_PATH)s/flames_sc.R
        --fastq %(infile)s
        --gtf %(flames_gtf)s
        --genome %(flames_fasta)s
        --outdir %(outdir)s
        --threads %(job_threads)s
        --expect_cells %(expect_cells)s
        --min_support %(min_support)s
        --do_discovery %(do_discovery)s
        %(barcodes_option)s
        && touch %(outfile)s
    """

    P.run(statement)


# -----------------------------------------------
# Combined count matrices (spliced + unspliced)
# -----------------------------------------------

@follows(mkdir("combined_counts"))
@transform(tag_bam_with_barcodes,
           regex(r"tagged/(\S+)\.tagged\.bam"),
           r"combined_counts/\1.combined_counts.rds")
def count_combined(infile, outfile):
    """
    Generate combined count matrices including BOTH spliced and unspliced reads.
    
    This is essential for nuclei sequencing where a significant fraction of
    transcripts are unspliced pre-mRNA. The output includes:
    - Gene-level counts (spliced + unspliced combined)
    - Transcript-level counts (spliced + unspliced combined)
    - Separate spliced/unspliced layers for velocity analysis
    
    All reads mapping to a gene (exonic OR intronic) are counted to capture
    the full transcriptional output from each cell.
    """

    R_SRC_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), "R"))

    gtf = PARAMS["featurecounts_gtf"]
    job_memory = PARAMS.get("combined_memory", "32G")

    statement = """
        Rscript %(R_SRC_PATH)s/combined_counts.R
        --bam %(infile)s
        --gtf %(gtf)s
        --output %(outfile)s
    """

    P.run(statement)


# -----------------------------------------------
# Gene-level quantification with featureCounts
# (includes both exonic and gene-body for unspliced)
# -----------------------------------------------

@follows(mkdir("genecounts"))
@transform(tag_bam_with_barcodes,
           regex(r"tagged/(\S+)\.tagged\.bam"),
           r"genecounts/\1.gene_counts.tsv")
def count_genes(infile, outfile):
    """
    Count reads per gene using featureCounts.
    Uses settings appropriate for long reads and nuclei data.
    
    Two-pass counting to capture both spliced and unspliced:
    1. Exon counts (spliced reads)
    2. Gene-body counts (includes intronic = unspliced)
    
    Final output combines both for total gene expression.
    """

    gtf = PARAMS["featurecounts_gtf"]
    job_threads = PARAMS.get("featurecounts_threads", 4)

    exon_counts = outfile.replace(".gene_counts.tsv", ".exon_counts.tsv")
    gene_counts = outfile.replace(".gene_counts.tsv", ".genebody_counts.tsv")

    # Count exonic reads (spliced)
    # -L for long reads, -M for multimappers, -O for overlapping features
    # --fraction to handle multi-mapping reads
    statement = """
        featureCounts -L -M -O --fraction
        -t exon -g gene_id
        -a %(gtf)s
        -T %(job_threads)s
        -o %(exon_counts)s
        %(infile)s
        &&
        featureCounts -L -M -O --fraction
        -t gene -g gene_id
        -a %(gtf)s
        -T %(job_threads)s
        -o %(gene_counts)s
        %(infile)s
        &&
        echo "Combining exon and gene counts..." &&
        paste %(exon_counts)s %(gene_counts)s > %(outfile)s
    """

    P.run(statement)


# -----------------------------------------------
# Velocity matrices (separate spliced/unspliced)
# -----------------------------------------------

@follows(mkdir("velocity"))
@transform(tag_bam_with_barcodes,
           regex(r"tagged/(\S+)\.tagged\.bam"),
           r"velocity/\1.velocity_counts.rds")
def count_velocity(infile, outfile):
    """
    Generate SEPARATE spliced and unspliced count matrices for RNA velocity.
    
    Unlike combined_counts which sums spliced + unspliced, this step keeps
    them separate for use with scVelo or velocyto for trajectory analysis.
    
    Uses exon/intron annotations to classify reads:
    - Spliced: reads with splice junctions (N in CIGAR) overlapping exons
    - Unspliced: reads without splice junctions OR overlapping introns
    
    Output: RDS file with spliced, unspliced, and ambiguous matrices

    Note: the IsoQuant route (build_splice_matrices) provides an alternative
    spliced/unspliced product derived from UMI-deduplicated molecule
    assignments and is the recommended source for downstream velocity analysis.
    This task is retained for compatibility.
    """

    R_SRC_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), "R"))

    gtf = PARAMS["velocity_gtf"]
    job_memory = PARAMS.get("velocity_memory", "32G")

    statement = """
        Rscript %(R_SRC_PATH)s/velocity_counts.R
        --bam %(infile)s
        --gtf %(gtf)s
        --output %(outfile)s
    """

    P.run(statement)


# -----------------------------------------------
# Splice matrices from IsoQuant output
# -----------------------------------------------

@follows(mkdir("splice_matrices"))
@transform(quantify_isoquant,
           regex(r"isoquant/(\S+)/isoquant\.sentinel"),
           r"splice_matrices/\1.splice_matrices.sentinel")
def build_splice_matrices(infile, outfile):
    """
    Build spliced transcript-level and unspliced gene-level AnnData matrices
    from IsoQuant single-cell output.

    Reads IsoQuant's native barcode-grouped count matrices for molecule totals
    and parses the per-read assignment file (read_info.tsv or
    read_assignments.tsv) to label each molecule as spliced, unspliced, or
    ambiguous. Produces:
      - {sample}.transcript.spliced.h5ad  (transcript x barcode, spliced)
      - {sample}.gene.h5ad                (gene x barcode, spliced/unspliced/total layers)
      - MatrixMarket exports alongside each h5ad
      - {sample}.barcode_qc.tsv           (per-barcode QC table)

    A reconciliation check compares spliced+unspliced+ambiguous totals against
    IsoQuant's native matrix; warnings are emitted if divergence exceeds the
    configured tolerance.
    """

    # Must be a local so P.run() interpolation finds it in locals()
    PYTHON_SRC_PATH = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "python"))

    sample = os.path.basename(os.path.dirname(infile))
    # IsoQuant writes output into a subdirectory named after the sample prefix
    # (-p) inside the -o directory, so the count files are at
    # isoquant/{sample}/{sample}/ not isoquant/{sample}/
    isoquant_dir = os.path.join(os.path.dirname(infile), sample)
    outdir = os.path.dirname(outfile)
    tolerance = PARAMS.get("isoquant_reconcile_tolerance", 0.01)

    job_memory = PARAMS.get("splice_qc_memory", "8G")

    statement = """
        python %(PYTHON_SRC_PATH)s/isoquant_matrices.py
        --isoquant-dir %(isoquant_dir)s
        --sample %(sample)s
        --outdir %(outdir)s
        --tolerance %(tolerance)s
        && touch %(outfile)s
    """

    P.run(statement)


# -----------------------------------------------
# Splice proportion QC
# -----------------------------------------------

@follows(mkdir("qc_splice"))
@merge(build_splice_matrices,
       "qc_splice/splice_proportion_mqc.tsv")
def qc_splice_proportion(infiles, outfile):
    """
    Flag per-barcode outliers on unspliced_fraction using the median absolute
    deviation (MAD) method and write a MultiQC custom-content file.

    Concatenates the per-sample barcode_qc.tsv tables produced by
    build_splice_matrices, computes MAD-based outlier flags on
    unspliced_fraction, cross-tabulates against total_umis and n_genes bins,
    and writes a *_mqc.tsv file picked up automatically by MultiQC.
    """

    # Must be a local so P.run() interpolation finds it in locals()
    PYTHON_SRC_PATH = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "python"))

    # Collect per-sample QC tables from splice_matrices/
    # Each sentinel lives at splice_matrices/{sample}.splice_matrices.sentinel;
    # the QC table is splice_matrices/{sample}.barcode_qc.tsv
    qc_tables = " ".join(
        f.replace(".splice_matrices.sentinel", ".barcode_qc.tsv")
        for f in infiles
    )
    mad_multiplier = PARAMS.get("splice_qc_mad_multiplier", 3.0)
    job_memory = PARAMS.get("splice_qc_memory", "4G")

    statement = """
        python %(PYTHON_SRC_PATH)s/splice_qc.py
        --qc-tables %(qc_tables)s
        --mad-multiplier %(mad_multiplier)s
        --outfile %(outfile)s
    """

    P.run(statement)


# -----------------------------------------------
# IsoQuant interactive QC report (static HTML export)
# -----------------------------------------------

@follows(mkdir("isoquant_report"))
@transform(build_splice_matrices,
           regex(r"splice_matrices/(\S+)\.splice_matrices\.sentinel"),
           r"isoquant_report/\1/report.html")
def generate_isoquant_report(infile, outfile):
    """
    Generate a static IsoQuant QC HTML report and a config.yaml for the
    interactive Streamlit app.

    Runs headless (no Streamlit server). The HTML bundles Plotly figures for
    read-assignment QC, count matrix QC, gene/isoform comparison, and
    splicing structural summaries. Open the interactive app afterwards with:

        streamlit run isoquant_report/app.py -- --config isoquant_report/{sample}/config.yaml
    """

    sample = infile.replace(".splice_matrices.sentinel", "").split("/")[-1]
    isoquant_dir = os.path.join("isoquant", sample, sample)
    splice_dir = "splice_matrices"
    outdir = os.path.dirname(outfile)

    gene_h5ad = os.path.join(splice_dir, "{}.gene.h5ad".format(sample))
    tx_h5ad = os.path.join(
        splice_dir, "{}.transcript.spliced.h5ad".format(sample))
    barcode_qc = os.path.join(splice_dir, "{}.barcode_qc.tsv".format(sample))

    job_memory = PARAMS.get("isoquant_report_memory", "16G")
    write_config = PARAMS.get("isoquant_report_write_config", True)
    write_config_flag = "--write-config" if write_config else ""

    # Parent of isoquant_report/ package on PYTHONPATH for python -m isoquant_report
    ISOQUANT_REPORT_ROOT = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "..", "isoquant_report"))

    statement = """
        PYTHONPATH=%(ISOQUANT_REPORT_ROOT)s
        python -m isoquant_report
        --isoquant-dir %(isoquant_dir)s
        --sample %(sample)s
        --gene-h5ad %(gene_h5ad)s
        --transcript-h5ad %(tx_h5ad)s
        --barcode-qc %(barcode_qc)s
        --outdir %(outdir)s
        %(write_config_flag)s
    """

    P.run(statement)


# -----------------------------------------------
# QC: NanoPlot
# -----------------------------------------------

@follows(mkdir("qc_nanoplot"))
@transform(align_minimap2,
           regex(r"aligned/(\S+)\.bam"),
           r"qc_nanoplot/\1/NanoStats.txt")
def qc_nanoplot(infile, outfile):
    """
    Run NanoPlot on aligned BAM files for long-read QC metrics.
    """

    outdir = os.path.dirname(outfile)

    job_threads = PARAMS.get("nanoplot_threads", 4)
    job_memory = PARAMS.get("nanoplot_memory", "8G")

    statement = """
        NanoPlot --bam %(infile)s 
        -o %(outdir)s 
        --tsv_stats 
        --plots dot 
        -t %(job_threads)s
    """

    P.run(statement)


# -----------------------------------------------
# QC: Cell barcode statistics
# -----------------------------------------------

@follows(mkdir("qc_cells"))
@merge(run_blaze, "qc_cells/barcode_summary.txt")
def summarize_barcodes(infiles, outfile):
    """
    Summarize cell barcode assignment statistics across all samples.
    """

    import pandas as pd

    dfs = []
    for infile in infiles:
        sample = os.path.basename(infile).replace("_barcode_stats.txt", "")
        df = pd.read_csv(infile, sep="\t")
        df["sample"] = sample
        dfs.append(df)

    combined = pd.concat(dfs, ignore_index=True)
    combined.to_csv(outfile, sep="\t", index=False)


# -----------------------------------------------
# MultiQC: Aggregate reports
# -----------------------------------------------

@follows(qc_nanoplot, count_genes, summarize_barcodes, qc_splice_proportion)
@merge([align_minimap2, "qc_nanoplot/*", "genecounts/*", "qc_splice/*"],
       "multiqc/multiqc_report.html")
def multiqc(infiles, outfile):
    """
    Aggregate all QC reports using MultiQC.
    """

    outdir = os.path.dirname(outfile)

    statement = """
        export LC_ALL=en_US.UTF-8 &&
        export LANG=en_US.UTF-8 &&
        multiqc -f -n multiqc_report.html -o %(outdir)s .
    """

    P.run(statement)


# -----------------------------------------------
# Pipeline targets
# -----------------------------------------------

@follows(run_flames, count_genes, count_velocity, multiqc,
         quantify_isoquant, build_splice_matrices, qc_splice_proportion,
         generate_isoquant_report)
def full():
    """
    Run the complete pipeline including alignment, FLAMES quantification,
    IsoQuant transcript quantification (concurrent with FLAMES), gene counts,
    velocity matrices, and all QC.

    FLAMES runs from FASTQ for novel isoform discovery and its own
    quantification. IsoQuant runs from the tagged BAM for UMI-deduplicated
    transcript and spliced/unspliced gene matrices. Both are scheduled
    concurrently by ruffus as they are independent of each other.
    """
    pass


@follows(align_minimap2, run_blaze, tag_bam_with_barcodes)
def align():
    """
    Run alignment and barcode tagging only.
    """
    pass


@follows(run_flames)
def flames():
    """
    Run FLAMES transcript analysis only (requires tagged BAMs).
    """
    pass


@follows(run_flames, count_genes, count_velocity,
         quantify_isoquant, build_splice_matrices, qc_splice_proportion)
def quantify():
    """
    Run quantification only (requires aligned FASTQ/BAMs upstream).

    Runs both FLAMES (from FASTQ, novel isoform discovery) and IsoQuant
    (from the tagged BAM, UMI-deduplicated spliced/unspliced matrices)
    concurrently, plus featureCounts gene counts and velocity matrices.
    """
    pass


@follows(qc_nanoplot, summarize_barcodes, multiqc, generate_isoquant_report)
def qc():
    """
    Run QC only, including IsoQuant static HTML report generation.
    """
    pass


@follows(generate_isoquant_report)
def isoquant_report():
    """
    Generate IsoQuant QC HTML reports only (requires splice matrices upstream).
    """
    pass


def main(argv=None):
    if argv is None:
        argv = sys.argv
    P.main(argv)


if __name__ == "__main__":
    sys.exit(P.main(sys.argv))
