"""===========================
Pipeline sclong
===========================

Overview
========

This pipeline performs analysis of 10x Genomics single-cell long-read RNA-seq
data from nuclei sequencing (ONT). The workflow handles both full-length and
spliced reads with quantification at both gene and transcript levels.

Supports both 10x 5' and 3' chemistries.

Key features:
- Cell barcode and UMI extraction using BLAZE (supports 5' and 3' kits)
- Splice-aware alignment with minimap2
- Transcript discovery and quantification using FLAMES
- Combined gene-level and transcript-level count matrices (spliced + unspliced)
- Separate spliced/unspliced matrices for RNA velocity analysis
- Handling of both spliced and unspliced reads (important for nuclei)

Usage
=====

To run locally:

    python pipeline_sclong.py make full --local -j 8

Configuration
-------------

The pipeline requires a configured :file:`pipeline.yml` file.

Default configuration files can be generated by executing:

   python <srcdir>/pipeline_sclong.py config

Important: Set the correct kit type in pipeline.yml:
- kit: 3v3  # For 10x 3' v3 chemistry
- kit: 5v2  # For 10x 5' v2 chemistry

Input files
-----------

* Fastq files from 10x ONT single-cell sequencing (*.fastq.gz or *.fastq)
* Reference genome (fasta)
* Annotation file (GTF)
* 10x barcode whitelist file (3M-february-2018.txt for v3)

Requirements
------------

* BLAZE - for cell barcode assignment (handles 5' and 3' kits)
* minimap2 - for splice-aware alignment
* samtools - for BAM processing
* FLAMES (R package) - for single-cell isoform analysis
* featureCounts - for gene-level counting

Pipeline output
===============

* Cell barcode assignments (blaze/)
* Aligned BAM files with cell barcode tags (tagged/)
* Combined gene-level count matrix - spliced + unspliced (combined_counts/)
* Transcript-level count matrix (flames/)
* Separate spliced/unspliced matrices for velocity (velocity/)
* Novel transcript GTF (flames/)
* QC reports (multiqc/)

Output count matrices include BOTH spliced and unspliced reads to capture
the full transcriptome from nuclei, where unspliced pre-mRNA is abundant.

Processing steps
================

1. BLAZE barcode assignment from long reads (kit-aware: 5' or 3')
2. Minimap2 splice-aware alignment
3. BAM tagging with cell barcodes and UMIs
4. FLAMES transcript discovery and quantification
5. Combined gene-level counting (spliced + unspliced)
6. Separate velocity matrices (spliced/unspliced for scVelo)
7. QC and MultiQC reporting

Code
====

"""

import sys
import os
from ruffus import *
import cgatcore.pipeline as P
import cgatcore.experiment as E

# load options from the config file
PARAMS = P.get_parameters(
    ["%s/pipeline.yml" % os.path.splitext(__file__)[0],
     "../pipeline.yml",
     "pipeline.yml"])


SEQUENCESUFFIXES = ("*.fastq.gz",
                    "*.fastq",
                    "*.fq.gz",
                    "*.fq")

SEQUENCEFILES = tuple([os.path.join('.', suffix_name)
                       for suffix_name in SEQUENCESUFFIXES])

SEQUENCEFILES_REGEX = regex(
    r".*/(\S+)\.(fastq\.gz|fastq|fq\.gz|fq)")


# -----------------------------------------------
# BLAZE: Cell barcode assignment (10x 5' and 3' kits)
# -----------------------------------------------

@follows(mkdir("blaze"))
@transform(SEQUENCEFILES,
           SEQUENCEFILES_REGEX,
           r"blaze/\1_putative_bc.csv")
def run_blaze(infile, outfile):
    """
    Run BLAZE to identify cell barcodes from 10x long reads.
    BLAZE uses a probabilistic model to assign 10x-style barcodes
    to long reads based on the barcode whitelist.

    Supports both 10x 5' and 3' chemistries:
    - 3' kit (3v3): barcode + UMI at 3' end near poly-A tail
    - 5' kit (5v2): barcode + UMI at 5' end of read

    Parameters from pipeline.yml:
        blaze_kit: 10x kit type (3v3, 5v2, etc.)
        blaze_whitelist: path to 10x barcode whitelist
        blaze_expect_cells: expected number of cells
    """

    outdir = os.path.dirname(outfile)
    basename = os.path.basename(infile).split('.')[0]

    job_threads = PARAMS.get("blaze_threads", 8)
    job_memory = PARAMS.get("blaze_memory", "16G")

    whitelist = PARAMS["blaze_whitelist"]
    kit_type = PARAMS.get("blaze_kit", "3v3")  # Default to 3' v3 chemistry
    expect_cells = PARAMS.get("blaze_expect_cells", 5000)
    blaze_options = PARAMS.get("blaze_options", "")

    statement = """
        blaze 
        --kit %(kit_type)s
        --expect-cells %(expect_cells)s
        --threads %(job_threads)s
        %(blaze_options)s
        --output-prefix %(outdir)s/%(basename)s
        %(whitelist)s
        %(infile)s
    """

    P.run(statement)


# -----------------------------------------------
# Generate splice junction BED from GTF annotation
# -----------------------------------------------

@follows(mkdir("aligned"))
@transform(PARAMS.get("minimap2_gtf", PARAMS.get("featurecounts_gtf", "")),
           regex(r"(.*)"),
           r"aligned/junctions.bed")
def generate_junc_bed(infile, outfile):
    """
    Convert GTF annotation to a splice junction BED file using paftools.js.
    This improves minimap2 splice alignment accuracy by providing known
    splice sites, helping to better distinguish spliced from unspliced reads.
    """

    job_memory = PARAMS.get("minimap2_memory", "8G")

    if infile.endswith(".gz"):
        cat_cmd = "zcat"
    else:
        cat_cmd = "cat"

    statement = """
        %(cat_cmd)s %(infile)s
        | paftools.js gff2bed /dev/stdin
        > %(outfile)s
    """

    P.run(statement)


# -----------------------------------------------
# Alignment with minimap2 (splice-aware)
# -----------------------------------------------

@follows(generate_junc_bed)
@transform(SEQUENCEFILES,
           SEQUENCEFILES_REGEX,
           r"aligned/\1.bam")
def align_minimap2(infile, outfile):
    """
    Align reads using minimap2 with splice-aware settings.
    Uses settings optimized for single-cell long-read data.

    For nuclei data, -ax splice maps to the genome so both spliced
    and unspliced (intron-retaining) reads are captured. The --junc-bed
    file provides known splice sites to improve alignment accuracy.

    Parameters from pipeline.yml:
        genome_fasta: path to reference genome fasta
        minimap2_options: additional minimap2 options
        minimap2_gtf: GTF used to generate junction BED
    """

    job_threads = PARAMS.get("minimap2_threads", 16)
    job_memory = PARAMS.get("minimap2_memory", "8G")

    genome_fasta = PARAMS["genome_fasta"]
    minimap2_options = PARAMS.get("minimap2_options", "-ax splice -uf -k14")
    junc_bed = "aligned/junctions.bed"

    statement = """
        minimap2 %(minimap2_options)s
        --junc-bed %(junc_bed)s
        -t %(job_threads)s
        %(genome_fasta)s
        %(infile)s
        | samtools sort -@ %(job_threads)s -O bam -o %(outfile)s -
        && samtools index %(outfile)s
    """

    P.run(statement)


# -----------------------------------------------
# Tag BAM with cell barcodes (10x compatible)
# -----------------------------------------------

@follows(mkdir("tagged"), run_blaze)
@transform(align_minimap2,
           regex(r"aligned/(\S+)\.bam"),
           r"tagged/\1.tagged.bam")
def tag_bam_with_barcodes(infile, outfile):
    """
    Add cell barcode (CB) and UMI (UB) tags to BAM file
    using BLAZE barcode assignments.
    
    Tags are added in 10x-compatible format:
    - CB:Z: cell barcode
    - UB:Z: UMI sequence
    """

    # Get corresponding BLAZE output
    basename = os.path.basename(infile).replace(".bam", "")
    blaze_bc = "blaze/{}_putative_bc.csv".format(basename)

    job_memory = PARAMS.get("tag_memory", "16G")

    R_SRC_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), "R"))

    statement = """
        Rscript %(R_SRC_PATH)s/tag_bam_barcodes.R
        --bam %(infile)s
        --barcodes %(blaze_bc)s
        --output %(outfile)s
        && samtools index %(outfile)s
    """

    P.run(statement)


# -----------------------------------------------
# FLAMES: Transcript discovery and quantification
# -----------------------------------------------

@follows(mkdir("flames"))
@merge(tag_bam_with_barcodes, "flames/flames_output.sentinel")
def run_flames(infiles, outfile):
    """
    Run FLAMES for single-cell transcript discovery and quantification.
    FLAMES performs:
    - Novel isoform identification
    - Transcript-level quantification
    - Gene-level quantification
    - Spliced/unspliced matrix generation for RNA velocity

    Parameters from pipeline.yml:
        flames_gtf: annotation GTF file
        flames_fasta: reference genome fasta
    """

    R_SRC_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), "R"))

    # Create input file list
    bam_list = "flames/bam_files.txt"
    with open(bam_list, "w") as f:
        for infile in infiles:
            f.write(os.path.abspath(infile) + "\n")

    outdir = "flames"

    job_threads = PARAMS.get("flames_threads", 8)
    job_memory = PARAMS.get("flames_memory", "64G")

    statement = """
        Rscript %(R_SRC_PATH)s/flames_sc.R
        --bam_list %(bam_list)s
        --gtf %(flames_gtf)s
        --genome %(flames_fasta)s
        --outdir %(outdir)s
        --threads %(job_threads)s
        && touch %(outfile)s
    """

    P.run(statement)


# -----------------------------------------------
# Combined count matrices (spliced + unspliced)
# -----------------------------------------------

@follows(mkdir("combined_counts"))
@transform(tag_bam_with_barcodes,
           regex(r"tagged/(\S+)\.tagged\.bam"),
           r"combined_counts/\1.combined_counts.rds")
def count_combined(infile, outfile):
    """
    Generate combined count matrices including BOTH spliced and unspliced reads.
    
    This is essential for nuclei sequencing where a significant fraction of
    transcripts are unspliced pre-mRNA. The output includes:
    - Gene-level counts (spliced + unspliced combined)
    - Transcript-level counts (spliced + unspliced combined)
    - Separate spliced/unspliced layers for velocity analysis
    
    All reads mapping to a gene (exonic OR intronic) are counted to capture
    the full transcriptional output from each cell.
    """

    R_SRC_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), "R"))

    gtf = PARAMS["featurecounts_gtf"]
    job_memory = PARAMS.get("combined_memory", "32G")

    statement = """
        Rscript %(R_SRC_PATH)s/combined_counts.R
        --bam %(infile)s
        --gtf %(gtf)s
        --output %(outfile)s
    """

    P.run(statement)


# -----------------------------------------------
# Gene-level quantification with featureCounts
# (includes both exonic and gene-body for unspliced)
# -----------------------------------------------

@follows(mkdir("genecounts"))
@transform(tag_bam_with_barcodes,
           regex(r"tagged/(\S+)\.tagged\.bam"),
           r"genecounts/\1.gene_counts.tsv")
def count_genes(infile, outfile):
    """
    Count reads per gene using featureCounts.
    Uses settings appropriate for long reads and nuclei data.
    
    Two-pass counting to capture both spliced and unspliced:
    1. Exon counts (spliced reads)
    2. Gene-body counts (includes intronic = unspliced)
    
    Final output combines both for total gene expression.
    """

    gtf = PARAMS["featurecounts_gtf"]
    job_threads = PARAMS.get("featurecounts_threads", 4)

    exon_counts = outfile.replace(".gene_counts.tsv", ".exon_counts.tsv")
    gene_counts = outfile.replace(".gene_counts.tsv", ".genebody_counts.tsv")

    # Count exonic reads (spliced)
    # -L for long reads, -M for multimappers, -O for overlapping features
    # --fraction to handle multi-mapping reads
    statement = """
        featureCounts -L -M -O --fraction
        -t exon -g gene_id
        -a %(gtf)s
        -T %(job_threads)s
        -o %(exon_counts)s
        %(infile)s
        &&
        featureCounts -L -M -O --fraction
        -t gene -g gene_id
        -a %(gtf)s
        -T %(job_threads)s
        -o %(gene_counts)s
        %(infile)s
        &&
        echo "Combining exon and gene counts..." &&
        paste %(exon_counts)s %(gene_counts)s > %(outfile)s
    """

    P.run(statement)


# -----------------------------------------------
# Velocity matrices (separate spliced/unspliced)
# -----------------------------------------------

@follows(mkdir("velocity"))
@transform(tag_bam_with_barcodes,
           regex(r"tagged/(\S+)\.tagged\.bam"),
           r"velocity/\1.velocity_counts.rds")
def count_velocity(infile, outfile):
    """
    Generate SEPARATE spliced and unspliced count matrices for RNA velocity.
    
    Unlike combined_counts which sums spliced + unspliced, this step keeps
    them separate for use with scVelo or velocyto for trajectory analysis.
    
    Uses exon/intron annotations to classify reads:
    - Spliced: reads with splice junctions (N in CIGAR) overlapping exons
    - Unspliced: reads without splice junctions OR overlapping introns
    
    Output: RDS file with spliced, unspliced, and ambiguous matrices
    """

    R_SRC_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), "R"))

    gtf = PARAMS["velocity_gtf"]
    job_memory = PARAMS.get("velocity_memory", "32G")

    statement = """
        Rscript %(R_SRC_PATH)s/velocity_counts.R
        --bam %(infile)s
        --gtf %(gtf)s
        --output %(outfile)s
    """

    P.run(statement)


# -----------------------------------------------
# QC: NanoPlot
# -----------------------------------------------

@follows(mkdir("qc_nanoplot"))
@transform(align_minimap2,
           regex(r"aligned/(\S+)\.bam"),
           r"qc_nanoplot/\1/NanoStats.txt")
def qc_nanoplot(infile, outfile):
    """
    Run NanoPlot on aligned BAM files for long-read QC metrics.
    """

    outdir = os.path.dirname(outfile)

    job_threads = PARAMS.get("nanoplot_threads", 4)
    job_memory = PARAMS.get("nanoplot_memory", "8G")

    statement = """
        NanoPlot --bam %(infile)s 
        -o %(outdir)s 
        --tsv_stats 
        --plots dot 
        -t %(job_threads)s
    """

    P.run(statement)


# -----------------------------------------------
# QC: Cell barcode statistics
# -----------------------------------------------

@follows(mkdir("qc_cells"))
@merge(run_blaze, "qc_cells/barcode_summary.txt")
def summarize_barcodes(infiles, outfile):
    """
    Summarize cell barcode assignment statistics across all samples.
    """

    import pandas as pd

    dfs = []
    for infile in infiles:
        sample = os.path.basename(infile).replace("_barcode_stats.txt", "")
        df = pd.read_csv(infile, sep="\t")
        df["sample"] = sample
        dfs.append(df)

    combined = pd.concat(dfs, ignore_index=True)
    combined.to_csv(outfile, sep="\t", index=False)


# -----------------------------------------------
# MultiQC: Aggregate reports
# -----------------------------------------------

@follows(qc_nanoplot, count_genes, summarize_barcodes)
@merge([align_minimap2, "qc_nanoplot/*", "genecounts/*"],
       "multiqc/multiqc_report.html")
def multiqc(infiles, outfile):
    """
    Aggregate all QC reports using MultiQC.
    """

    outdir = os.path.dirname(outfile)

    statement = """
        export LC_ALL=en_US.UTF-8 &&
        export LANG=en_US.UTF-8 &&
        multiqc -f -n multiqc_report.html -o %(outdir)s .
    """

    P.run(statement)


# -----------------------------------------------
# Pipeline targets
# -----------------------------------------------

@follows(run_flames, count_genes, count_velocity, multiqc)
def full():
    """
    Run the complete pipeline including alignment, FLAMES quantification,
    gene counts, velocity matrices, and all QC.
    """
    pass


@follows(align_minimap2, run_blaze, tag_bam_with_barcodes)
def align():
    """
    Run alignment and barcode tagging only.
    """
    pass


@follows(run_flames)
def flames():
    """
    Run FLAMES transcript analysis only (requires tagged BAMs).
    """
    pass


@follows(count_genes, count_velocity)
def quantify():
    """
    Run quantification only (requires tagged BAMs).
    """
    pass


@follows(qc_nanoplot, summarize_barcodes, multiqc)
def qc():
    """
    Run QC only.
    """
    pass


def main(argv=None):
    if argv is None:
        argv = sys.argv
    P.main(argv)


if __name__ == "__main__":
    sys.exit(P.main(sys.argv))
