"""===========================
Pipeline sclong
===========================

Overview
========

This pipeline performs analysis of 10x Genomics single-cell long-read RNA-seq
data from nuclei sequencing (ONT). The workflow handles both full-length and
spliced reads with quantification at both gene and transcript levels.

Supports both 10x 5' and 3' chemistries.

Key features:
- Cell barcode and UMI extraction using BLAZE (supports 5' and 3' kits)
- Splice-aware alignment with minimap2
- Transcript discovery and quantification using IsoQuant (from tagged BAM):
  spliced transcript-level and unspliced gene-level AnnData matrices,
  per-barcode splicing-proportion QC surfaced in MultiQC
- Optional FLAMES (from FASTQ) for smaller samples — opt-in via ``make flames``
- Combined gene-level and transcript-level count matrices (spliced + unspliced)
- Separate spliced/unspliced matrices for RNA velocity analysis
- Handling of both spliced and unspliced reads (important for nuclei)

Usage
=====

To run locally:

    python pipeline_sclong.py make full --local -j 8

Configuration
-------------

The pipeline requires a configured :file:`pipeline.yml` file.

Default configuration files can be generated by executing:

   python <srcdir>/pipeline_sclong.py config

Important: Set the correct kit type in pipeline.yml:
- kit: 3v3  # For 10x 3' v3 chemistry
- kit: 5v2  # For 10x 5' v2 chemistry

Input files
-----------

* Fastq files from 10x ONT single-cell sequencing (*.fastq.gz or *.fastq)
* Reference genome (fasta)
* Annotation file (GTF)
* 10x barcode whitelist file (3M-february-2018.txt for v3)

Requirements
------------

* BLAZE - for cell barcode assignment (handles 5' and 3' kits)
* minimap2 - for splice-aware alignment
* samtools - for BAM processing
* IsoQuant - for single-cell transcript discovery and quantification
* featureCounts - for gene-level counting
* FLAMES (R package) - optional, smaller samples only (``make flames``)

Pipeline output
===============

* Cell barcode assignments (blaze/)
* Aligned BAM files with cell barcode tags (tagged/)
* BAM subsets for true cells only (tagged_cells/)
* IsoQuant SC outputs: transcript/gene count matrices (isoquant/)
* Spliced transcript AnnData and unspliced gene AnnData (splice_matrices/)
* Per-barcode splicing-proportion QC, MultiQC custom content (qc_splice/)
* Combined gene-level count matrix - spliced + unspliced (combined_counts/)
* Separate spliced/unspliced matrices for velocity (velocity/)
* Optional FLAMES isoform discovery / counts (flames/) — ``make flames``
* QC reports (multiqc/)
* Fusion predictions (fusions/) — opt-in via ``make fusions``
* Targeted translocation scan (targeted_fusions/) — opt-in via ``make targeted_fusions``
* Per-cell SNV VCF + genotype matrix (snv/) — opt-in via ``make variants``

Output count matrices include BOTH spliced and unspliced reads to capture
the full transcriptome from nuclei, where unspliced pre-mRNA is abundant.

Processing steps
================

1. BLAZE barcode assignment from long reads (kit-aware: 5' or 3')
2. Minimap2 splice-aware alignment
3. BAM tagging with cell barcodes and UMIs
4. IsoQuant transcript discovery and quantification (from tagged BAM):
   subset BAM to true cells, quantify with --barcoded_bam, derive
   spliced transcript and unspliced gene AnnData matrices, splice QC
5. Combined gene-level counting (spliced + unspliced)
6. Separate velocity matrices (spliced/unspliced for scVelo)
7. QC and MultiQC reporting (including splice-proportion outlier table)
8. (Opt-in) FLAMES from FASTQ for smaller samples (`make flames`)
9. (Opt-in) ctat-LR-fusion fusion calling on tagged BAMs (`make fusions`)
10. (Opt-in) Targeted translocation window scan per cell (`make targeted_fusions`)
11. (Opt-in) Per-cell longshot SNV calling + genotype matrix (`make variants`)

Code
====

"""

import sys
import os
from ruffus import *
import cgatcore.pipeline as P
import cgatcore.experiment as E

# load options from the config file
PARAMS = P.get_parameters(
    ["%s/pipeline.yml" % os.path.splitext(__file__)[0],
     "../pipeline.yml",
     "pipeline.yml"])


SEQUENCESUFFIXES = ("*.fastq.gz",
                    "*.fastq",
                    "*.fq.gz",
                    "*.fq")

SEQUENCEFILES = tuple([os.path.join('.', suffix_name)
                       for suffix_name in SEQUENCESUFFIXES])

SEQUENCEFILES_REGEX = regex(
    r".*/(\S+)\.(fastq\.gz|fastq|fq\.gz|fq)")


# -----------------------------------------------
# BLAZE: Cell barcode assignment (10x 5' and 3' kits)
# -----------------------------------------------

@follows(mkdir("blaze"))
@transform(SEQUENCEFILES,
           SEQUENCEFILES_REGEX,
           r"blaze/\1_putative_bc.csv")
def run_blaze(infile, outfile):
    """
    Run BLAZE to identify cell barcodes from 10x long reads.
    BLAZE uses a probabilistic model to assign 10x-style barcodes
    to long reads based on the barcode whitelist.

    Supports both 10x 5' and 3' chemistries:
    - 3' kit (3v3): barcode + UMI at 3' end near poly-A tail
    - 5' kit (5v2): barcode + UMI at 5' end of read

    Parameters from pipeline.yml:
        blaze_kit: 10x kit type (3v3, 5v2, etc.)
        blaze_whitelist: path to 10x barcode whitelist
        blaze_expect_cells: expected number of cells
    """

    outdir = os.path.dirname(outfile)
    basename = os.path.basename(infile).split('.')[0]

    job_threads = PARAMS.get("blaze_threads", 8)
    job_memory = PARAMS.get("blaze_memory", "16G")

    kit_type = PARAMS.get("blaze_kit", "3v3")  # Default to 3' v3 chemistry
    expect_cells = PARAMS.get("blaze_expect_cells", 5000)
    blaze_options = PARAMS.get("blaze_options", "")

    # BLAZE bundles the standard 10x whitelists and selects one based on the
    # kit version, so a whitelist only needs to be supplied for custom
    # (non-10x) barcodes via --full-bc-whitelist.
    whitelist = PARAMS.get("blaze_whitelist", "")
    if whitelist and os.path.exists(whitelist):
        whitelist_option = "--full-bc-whitelist %s" % whitelist
    else:
        whitelist_option = ""

    statement = """
        blaze
        --10x-kit-version %(kit_type)s
        --expect-cells %(expect_cells)s
        --threads %(job_threads)s
        %(whitelist_option)s
        %(blaze_options)s
        --output-prefix %(outdir)s/%(basename)s_
        %(infile)s
    """

    P.run(statement)


# -----------------------------------------------
# Generate splice junction BED from GTF annotation
# -----------------------------------------------

@follows(mkdir("aligned"))
@transform(PARAMS.get("minimap2_gtf", PARAMS.get("featurecounts_gtf", "")),
           regex(r"(.*)"),
           r"aligned/junctions.bed")
def generate_junc_bed(infile, outfile):
    """
    Convert GTF annotation to a splice junction BED file using paftools.js.
    This improves minimap2 splice alignment accuracy by providing known
    splice sites, helping to better distinguish spliced from unspliced reads.
    """

    job_memory = PARAMS.get("minimap2_memory", "8G")

    if infile.endswith(".gz"):
        cat_cmd = "zcat"
    else:
        cat_cmd = "cat"

    statement = """
        %(cat_cmd)s %(infile)s
        | paftools.js gff2bed /dev/stdin
        > %(outfile)s
    """

    P.run(statement)


# -----------------------------------------------
# Alignment with minimap2 (splice-aware)
# -----------------------------------------------

@follows(generate_junc_bed)
@transform(SEQUENCEFILES,
           SEQUENCEFILES_REGEX,
           r"aligned/\1.bam")
def align_minimap2(infile, outfile):
    """
    Align reads using minimap2 with splice-aware settings.
    Uses settings optimized for single-cell long-read data.

    For nuclei data, -ax splice maps to the genome so both spliced
    and unspliced (intron-retaining) reads are captured. The --junc-bed
    file provides known splice sites to improve alignment accuracy.

    Parameters from pipeline.yml:
        genome_fasta: path to reference genome fasta
        minimap2_options: additional minimap2 options
        minimap2_gtf: GTF used to generate junction BED
    """

    job_threads = PARAMS.get("minimap2_threads", 16)
    job_memory = PARAMS.get("minimap2_memory", "8G")

    genome_fasta = PARAMS["genome_fasta"]
    minimap2_options = PARAMS.get("minimap2_options", "-ax splice -uf -k14")
    junc_bed = "aligned/junctions.bed"

    # Per-thread memory for samtools sort. The default (768M/thread) silently
    # scales with -@, so for large runs this bounds the sort buffer explicitly.
    sort_memory = PARAMS.get("minimap2_sort_memory", "1G")
    # Keep sort temp files next to the output (on the working disk) rather than
    # in a possibly-small /tmp, and give them a unique prefix per BAM.
    sort_tmp = outfile + ".sorttmp"
    # Capture minimap2's own stderr separately so that when it exits abnormally
    # (OOM-kill, crash, etc.) we keep its real error message instead of only
    # seeing samtools' downstream "truncated file" complaint about the broken pipe.
    minimap2_log = outfile + ".minimap2.log"

    # pipefail ensures a minimap2 failure (e.g. OOM-kill or a corrupt input
    # FASTQ) propagates as an error instead of being masked by samtools, which
    # would otherwise abort on the partial stream and leave a half-written BAM.
    statement = """
        set -o pipefail &&
        minimap2 %(minimap2_options)s
        --junc-bed %(junc_bed)s
        -t %(job_threads)s
        %(genome_fasta)s
        %(infile)s
        2> %(minimap2_log)s
        | samtools sort -@ %(job_threads)s -m %(sort_memory)s
        -T %(sort_tmp)s -O bam -o %(outfile)s -
        && samtools index %(outfile)s
    """

    P.run(statement)


# -----------------------------------------------
# Tag BAM with cell barcodes (10x compatible)
# -----------------------------------------------

@follows(mkdir("tagged"), run_blaze)
@transform(align_minimap2,
           regex(r"aligned/(\S+)\.bam"),
           r"tagged/\1.tagged.bam")
def tag_bam_with_barcodes(infile, outfile):
    """
    Add cell barcode (CB) and UMI (UB) tags to BAM file using BLAZE step-3
    read-to-whitelist assignment (error-corrected CB/UB), not raw putative_bc.

    Tags are added in 10x-compatible format:
    - CB:Z: corrected cell barcode (whitelist sequence)
    - UB:Z: UMI sequence (INDEL-adjusted when applicable)
    """

    # Get corresponding BLAZE outputs
    basename = os.path.basename(infile).replace(".bam", "")
    blaze_bc = "blaze/{}_putative_bc.csv".format(basename)
    blaze_whitelist = "blaze/{}_whitelist.csv".format(basename)

    # Assignment is CPU-bound (per-read whitelist edit distance). Give it
    # threads and enough RAM for the awk barcode map + BAM stream.
    job_threads = PARAMS.get("tag_threads", 8)
    job_memory = PARAMS.get("tag_memory", "32G")

    R_SRC_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), "R"))

    statement = """
        Rscript %(R_SRC_PATH)s/tag_bam_barcodes.R
        --bam %(infile)s
        --barcodes %(blaze_bc)s
        --whitelist %(blaze_whitelist)s
        --output %(outfile)s
        --threads %(job_threads)s
        && samtools index %(outfile)s
    """

    P.run(statement)


# -----------------------------------------------
# Subset tagged BAM to true cells before IsoQuant
# -----------------------------------------------

@follows(mkdir("tagged_cells"))
@transform(tag_bam_with_barcodes,
           regex(r"tagged/(\S+)\.tagged\.bam"),
           r"tagged_cells/\1.cells.bam")
def subset_cells(infile, outfile):
    """
    Subset the tagged BAM to barcodes in the BLAZE cell whitelist.

    IsoQuant is run with --barcoded_bam, which quantifies every CB tag it
    finds. Restricting to true cells here keeps deduplication and
    quantification clean and avoids processing ambient/noise barcodes.

    The whitelist is resolved in order:
      1. isoquant_cell_whitelist from pipeline.yml (supports {sample}
         placeholder for per-sample lists).
      2. blaze/{sample}_whitelist.csv produced by run_blaze.
      3. If neither exists the tagged BAM is symlinked through unchanged
         so the task remains idempotent.

    Strand assumption: minimap2 is run with -uf, so only forward-strand
    alignments are produced. IsoQuant inherits this strand orientation when
    reading the BAM. Wrong-strand intronic reads would contaminate the
    unspliced matrix; this is guarded against by the upstream -uf flag.

    Note on barcode format: BLAZE whitelists carry bare barcodes (no GEM-well
    suffix). When isoquant.strip_barcode_suffix is enabled, IsoQuant strips
    the dash suffix from CB tags before matching -- ensure the whitelist
    format is consistent with this setting.
    """

    sample = os.path.basename(infile).replace(".tagged.bam", "")

    job_memory = PARAMS.get("isoquant_memory", "16G")

    # Resolve cell whitelist
    wl_param = PARAMS.get("isoquant_cell_whitelist", "")
    if wl_param:
        whitelist = wl_param.replace("{sample}", sample)
    else:
        whitelist = "blaze/{}_whitelist.csv".format(sample)

    if not os.path.exists(whitelist):
        # No whitelist available -- pass through with a symlink
        outbai = outfile + ".bai"
        inbai = infile + ".bai"
        statement = """
            ln -sf $(realpath %(infile)s) %(outfile)s
            && ln -sf $(realpath %(inbai)s) %(outbai)s
        """
        P.run(statement)
        return

    # Extract barcode column (first column, skip header lines starting with #)
    bc_list = outfile + ".bc_list.txt"

    # samtools view -D CB:<file> filters reads whose CB tag matches any
    # barcode in the file (one barcode per line, no header).
    # The BLAZE whitelist is CSV; take the first field, skip comment lines.
    statement = """
        grep -v '^#' %(whitelist)s
        | cut -d',' -f1
        | grep -v '^barcode' > %(bc_list)s
        && samtools view -h -b -D CB:%(bc_list)s %(infile)s
        | samtools sort -o %(outfile)s -
        && samtools index %(outfile)s
        && rm -f %(bc_list)s
    """

    P.run(statement)


# -----------------------------------------------
# IsoQuant: Transcript quantification (single-cell, from tagged BAM)
# -----------------------------------------------

@follows(mkdir("isoquant"))
@transform(subset_cells,
           regex(r"tagged_cells/(\S+)\.cells\.bam"),
           r"isoquant/\1/isoquant.sentinel")
def quantify_isoquant(infile, outfile):
    """
    Quantify transcripts and genes using IsoQuant in single-cell mode.

    IsoQuant reads cell barcodes and UMIs directly from the BAM tags set by
    BLAZE/tag_bam_barcodes.R (--barcoded_bam). UMI-based deduplication is
    performed natively by IsoQuant within each barcode x gene group.

    IsoQuant is the default discovery and quantification route for high cell
    counts. Model construction (novel isoforms of annotated genes) is on by
    default; set isoquant.no_model_construction: true to quantify against the
    reference only. Novel *gene* discovery is not performed in single-cell
    mode (IsoQuant limitation).

    Optional FLAMES (make flames) remains available for smaller samples.

    Strand: minimap2 upstream uses -uf (forward-strand only). IsoQuant
    inherits this orientation from the BAM. Intronic reads on the wrong
    strand would contaminate the unspliced matrix; the -uf flag prevents this.

    TODO: confirm that the installed IsoQuant version performs Levenshtein
    edit-distance UMI deduplication (expected ED3 for tenX_v3 mode). If
    exact-match-only dedup is used, ONT UMI error will inflate counts.
    The pre_collapse config key (isoquant.pre_collapse) is reserved for a
    future upstream correction step but is not implemented here.
    """

    sample = os.path.basename(os.path.dirname(outfile))
    outdir = os.path.dirname(outfile)

    job_threads = PARAMS.get("isoquant_threads", 8)
    job_memory = PARAMS.get("isoquant_memory", "64G")

    binary = PARAMS.get("isoquant_binary", "isoquant.py")
    mode = PARAMS.get("isoquant_mode", "tenX_v3")
    gtf = PARAMS.get("isoquant_gtf", PARAMS.get("flames_gtf",
                     PARAMS.get("featurecounts_gtf", "")))
    fasta = PARAMS.get("isoquant_fasta", PARAMS["genome_fasta"])
    barcode_tag = PARAMS.get("isoquant_barcode_tag", "CB")
    umi_tag = PARAMS.get("isoquant_umi_tag", "UB")
    strip_suffix = PARAMS.get("isoquant_strip_barcode_suffix", True)
    no_model = PARAMS.get("isoquant_no_model_construction", False)

    strip_opt = "--strip_barcode_suffix" if strip_suffix else ""
    model_opt = "--no_model_construction" if no_model else ""

    statement = """
        %(binary)s
        --reference %(fasta)s
        --genedb %(gtf)s
        --complete_genedb
        --bam %(infile)s
        --data_type nanopore
        --mode %(mode)s
        --barcoded_bam
        --barcode_tag %(barcode_tag)s
        --umi_tag %(umi_tag)s
        %(strip_opt)s
        %(model_opt)s
        --count_exons
        --counts_format mtx
        -o %(outdir)s
        -p %(sample)s
        -t %(job_threads)s
        && touch %(outfile)s
    """

    P.run(statement)


# -----------------------------------------------
# FLAMES: Transcript discovery and quantification
# -----------------------------------------------

@follows(mkdir("flames"), run_blaze)
@transform(SEQUENCEFILES,
           SEQUENCEFILES_REGEX,
           r"flames/\1/flames_output.sentinel")
def run_flames(infile, outfile):
    """
    Run FLAMES for single-cell transcript discovery and quantification.

    Opt-in only: set flames.run: true and ``make flames``. Prefer IsoQuant
    (default in ``make full`` / ``make quantify``) for high cell-count
    libraries — FLAMES can OOM on large nuclei samples.

    FLAMES 2.x runs end-to-end from FASTQ (it performs its own barcode
    demultiplexing and minimap2 alignment internally - it does not accept
    pre-aligned BAMs). One FLAMES run is performed per input sample.

    FLAMES performs:
    - Cell barcode demultiplexing (flexiplex against the BLAZE whitelist if
      available, otherwise BLAZE using the expected cell number)
    - Splice-aware genome alignment
    - Novel isoform identification
    - Transcript- and gene-level quantification

    Parameters from pipeline.yml:
        flames_run: must be true to execute
        flames_gtf: annotation GTF file
        flames_fasta: reference genome fasta
        flames_min_support_reads / flames_do_discovery
        blaze_expect_cells: expected number of cells
    """

    if not PARAMS.get("flames_run", False):
        raise ValueError(
            "flames_run is false. Set flames.run: true in pipeline.yml "
            "and run ``make flames``. For high cell counts prefer IsoQuant "
            "(included in ``make full`` / ``make quantify``)."
        )

    R_SRC_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), "R"))

    outdir = os.path.dirname(outfile)
    sample = os.path.basename(outdir)

    job_threads = PARAMS.get("flames_threads", 8)
    job_memory = PARAMS.get("flames_memory", "64G")

    min_support = PARAMS.get("flames_min_support_reads", 3)
    do_discovery = PARAMS.get("flames_do_discovery", True)
    expect_cells = PARAMS.get("blaze_expect_cells", 5000)

    # Reuse the BLAZE cell-barcode whitelist (if present) so FLAMES demultiplexes
    # against the already-identified barcodes instead of re-running BLAZE.
    whitelist = "blaze/{}_whitelist.csv".format(sample)
    barcodes_option = ""
    if os.path.exists(whitelist):
        barcodes_option = "--barcodes %s" % whitelist

    statement = """
        Rscript %(R_SRC_PATH)s/flames_sc.R
        --fastq %(infile)s
        --gtf %(flames_gtf)s
        --genome %(flames_fasta)s
        --outdir %(outdir)s
        --threads %(job_threads)s
        --expect_cells %(expect_cells)s
        --min_support %(min_support)s
        --do_discovery %(do_discovery)s
        %(barcodes_option)s
        && touch %(outfile)s
    """

    P.run(statement)


# -----------------------------------------------
# Combined count matrices (spliced + unspliced)
# -----------------------------------------------

@follows(mkdir("combined_counts"))
@transform(tag_bam_with_barcodes,
           regex(r"tagged/(\S+)\.tagged\.bam"),
           r"combined_counts/\1.combined_counts.rds")
def count_combined(infile, outfile):
    """
    Generate combined count matrices including BOTH spliced and unspliced reads.
    
    This is essential for nuclei sequencing where a significant fraction of
    transcripts are unspliced pre-mRNA. The output includes:
    - Gene-level counts (spliced + unspliced combined)
    - Transcript-level counts (spliced + unspliced combined)
    - Separate spliced/unspliced layers for velocity analysis
    
    All reads mapping to a gene (exonic OR intronic) are counted to capture
    the full transcriptional output from each cell.
    """

    R_SRC_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), "R"))

    gtf = PARAMS["featurecounts_gtf"]
    job_memory = PARAMS.get("combined_memory", "32G")

    statement = """
        Rscript %(R_SRC_PATH)s/combined_counts.R
        --bam %(infile)s
        --gtf %(gtf)s
        --output %(outfile)s
    """

    P.run(statement)


# -----------------------------------------------
# Gene-level quantification with featureCounts
# (includes both exonic and gene-body for unspliced)
# -----------------------------------------------

@follows(mkdir("genecounts"))
@transform(tag_bam_with_barcodes,
           regex(r"tagged/(\S+)\.tagged\.bam"),
           r"genecounts/\1.gene_counts.tsv")
def count_genes(infile, outfile):
    """
    Count reads per gene using featureCounts.
    Uses settings appropriate for long reads and nuclei data.
    
    Two-pass counting to capture both spliced and unspliced:
    1. Exon counts (spliced reads)
    2. Gene-body counts (includes intronic = unspliced)
    
    Final output combines both for total gene expression.
    """

    gtf = PARAMS["featurecounts_gtf"]
    job_threads = PARAMS.get("featurecounts_threads", 4)

    exon_counts = outfile.replace(".gene_counts.tsv", ".exon_counts.tsv")
    gene_counts = outfile.replace(".gene_counts.tsv", ".genebody_counts.tsv")

    # Count exonic reads (spliced)
    # -L for long reads, -M for multimappers, -O for overlapping features
    # --fraction to handle multi-mapping reads
    statement = """
        featureCounts -L -M -O --fraction
        -t exon -g gene_id
        -a %(gtf)s
        -T %(job_threads)s
        -o %(exon_counts)s
        %(infile)s
        &&
        featureCounts -L -M -O --fraction
        -t gene -g gene_id
        -a %(gtf)s
        -T %(job_threads)s
        -o %(gene_counts)s
        %(infile)s
        &&
        echo "Combining exon and gene counts..." &&
        paste %(exon_counts)s %(gene_counts)s > %(outfile)s
    """

    P.run(statement)


# -----------------------------------------------
# Velocity matrices (separate spliced/unspliced)
# -----------------------------------------------

@follows(mkdir("velocity"))
@transform(tag_bam_with_barcodes,
           regex(r"tagged/(\S+)\.tagged\.bam"),
           r"velocity/\1.velocity_counts.rds")
def count_velocity(infile, outfile):
    """
    Generate SEPARATE spliced and unspliced count matrices for RNA velocity.
    
    Unlike combined_counts which sums spliced + unspliced, this step keeps
    them separate for use with scVelo or velocyto for trajectory analysis.
    
    Uses exon/intron annotations to classify reads:
    - Spliced: reads with splice junctions (N in CIGAR) overlapping exons
    - Unspliced: reads without splice junctions OR overlapping introns
    
    Output: RDS file with spliced, unspliced, and ambiguous matrices

    Note: the IsoQuant route (build_splice_matrices) provides an alternative
    spliced/unspliced product derived from UMI-deduplicated molecule
    assignments and is the recommended source for downstream velocity analysis.
    This task is retained for compatibility.
    """

    R_SRC_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), "R"))

    gtf = PARAMS["velocity_gtf"]
    job_memory = PARAMS.get("velocity_memory", "32G")

    statement = """
        Rscript %(R_SRC_PATH)s/velocity_counts.R
        --bam %(infile)s
        --gtf %(gtf)s
        --output %(outfile)s
    """

    P.run(statement)


# -----------------------------------------------
# Splice matrices from IsoQuant output
# -----------------------------------------------

@follows(mkdir("splice_matrices"))
@transform(quantify_isoquant,
           regex(r"isoquant/(\S+)/isoquant\.sentinel"),
           r"splice_matrices/\1.splice_matrices.sentinel")
def build_splice_matrices(infile, outfile):
    """
    Build spliced transcript-level and unspliced gene-level AnnData matrices
    from IsoQuant single-cell output.

    Reads IsoQuant's native barcode-grouped count matrices for molecule totals
    and parses the per-read assignment file (read_info.tsv or
    read_assignments.tsv) to label each molecule as spliced, unspliced, or
    ambiguous. Produces:
      - {sample}.transcript.spliced.h5ad  (transcript x barcode, spliced)
      - {sample}.gene.h5ad                (gene x barcode, spliced/unspliced/total layers)
      - MatrixMarket exports alongside each h5ad
      - {sample}.barcode_qc.tsv           (per-barcode QC table)

    A reconciliation check compares spliced+unspliced+ambiguous totals against
    IsoQuant's native matrix; warnings are emitted if divergence exceeds the
    configured tolerance.
    """

    # Must be a local so P.run() interpolation finds it in locals()
    PYTHON_SRC_PATH = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "python"))

    sample = os.path.basename(os.path.dirname(infile))
    # IsoQuant writes output into a subdirectory named after the sample prefix
    # (-p) inside the -o directory, so the count files are at
    # isoquant/{sample}/{sample}/ not isoquant/{sample}/
    isoquant_dir = os.path.join(os.path.dirname(infile), sample)
    outdir = os.path.dirname(outfile)
    tolerance = PARAMS.get("isoquant_reconcile_tolerance", 0.01)

    job_memory = PARAMS.get("splice_qc_memory", "8G")

    statement = """
        python %(PYTHON_SRC_PATH)s/isoquant_matrices.py
        --isoquant-dir %(isoquant_dir)s
        --sample %(sample)s
        --outdir %(outdir)s
        --tolerance %(tolerance)s
        && touch %(outfile)s
    """

    P.run(statement)


# -----------------------------------------------
# Splice proportion QC
# -----------------------------------------------

@follows(mkdir("qc_splice"))
@merge(build_splice_matrices,
       "qc_splice/splice_proportion_mqc.tsv")
def qc_splice_proportion(infiles, outfile):
    """
    Flag per-barcode outliers on unspliced_fraction using the median absolute
    deviation (MAD) method and write a MultiQC custom-content file.

    Concatenates the per-sample barcode_qc.tsv tables produced by
    build_splice_matrices, computes MAD-based outlier flags on
    unspliced_fraction, cross-tabulates against total_umis and n_genes bins,
    and writes a *_mqc.tsv file picked up automatically by MultiQC.
    """

    # Must be a local so P.run() interpolation finds it in locals()
    PYTHON_SRC_PATH = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "python"))

    # Collect per-sample QC tables from splice_matrices/
    # Each sentinel lives at splice_matrices/{sample}.splice_matrices.sentinel;
    # the QC table is splice_matrices/{sample}.barcode_qc.tsv
    qc_tables = " ".join(
        f.replace(".splice_matrices.sentinel", ".barcode_qc.tsv")
        for f in infiles
    )
    mad_multiplier = PARAMS.get("splice_qc_mad_multiplier", 3.0)
    job_memory = PARAMS.get("splice_qc_memory", "4G")

    statement = """
        python %(PYTHON_SRC_PATH)s/splice_qc.py
        --qc-tables %(qc_tables)s
        --mad-multiplier %(mad_multiplier)s
        --outfile %(outfile)s
    """

    P.run(statement)


# -----------------------------------------------
# IsoQuant interactive QC report (static HTML export)
# -----------------------------------------------

@follows(mkdir("isoquant_report"))
@transform(build_splice_matrices,
           regex(r"splice_matrices/(\S+)\.splice_matrices\.sentinel"),
           r"isoquant_report/\1/report.html")
def generate_isoquant_report(infile, outfile):
    """
    Generate a static IsoQuant QC HTML report and a config.yaml for the
    interactive Streamlit app.

    Runs headless (no Streamlit server). The HTML bundles Plotly figures for
    read-assignment QC, count matrix QC, gene/isoform comparison, and
    splicing structural summaries. Open the interactive app afterwards with:

        streamlit run isoquant_report/app.py -- --config isoquant_report/{sample}/config.yaml
    """

    sample = infile.replace(".splice_matrices.sentinel", "").split("/")[-1]
    isoquant_dir = os.path.join("isoquant", sample, sample)
    splice_dir = "splice_matrices"
    outdir = os.path.dirname(outfile)

    gene_h5ad = os.path.join(splice_dir, "{}.gene.h5ad".format(sample))
    tx_h5ad = os.path.join(
        splice_dir, "{}.transcript.spliced.h5ad".format(sample))
    barcode_qc = os.path.join(splice_dir, "{}.barcode_qc.tsv".format(sample))

    job_memory = PARAMS.get("isoquant_report_memory", "16G")
    write_config = PARAMS.get("isoquant_report_write_config", True)
    write_config_flag = "--write-config" if write_config else ""

    # Parent of isoquant_report/ package on PYTHONPATH for python -m isoquant_report
    ISOQUANT_REPORT_ROOT = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "..", "isoquant_report"))

    statement = """
        PYTHONPATH=%(ISOQUANT_REPORT_ROOT)s
        python -m isoquant_report
        --isoquant-dir %(isoquant_dir)s
        --sample %(sample)s
        --gene-h5ad %(gene_h5ad)s
        --transcript-h5ad %(tx_h5ad)s
        --barcode-qc %(barcode_qc)s
        --outdir %(outdir)s
        %(write_config_flag)s
    """

    P.run(statement)


# -----------------------------------------------
# Fusion calling (ctat-LR-fusion, containerised)
# -----------------------------------------------

@follows(mkdir("fusions"))
@transform(tag_bam_with_barcodes,
           regex(r"tagged/(\S+)\.tagged\.bam"),
           r"fusions/\1/ctat-LR-fusion.fusion_predictions.tsv")
def find_fusions(infile, outfile):
    """
    Run ctat-LR-fusion on the tagged BAM (wf-single-cell ``find_fusions``).

    Requires fusion_call_fusions: true in pipeline.yml and a CTAT resource
    directory matching genome_fasta / annotation. Executed via a configurable
    container prefix (fusion_run_prefix).
    """
    if not PARAMS.get("fusion_call_fusions", False):
        raise ValueError(
            "fusion_call_fusions is false. Set fusion.call_fusions: true "
            "in pipeline.yml and run ``make fusions``."
        )

    sample = os.path.basename(infile).replace(".tagged.bam", "")
    ctat_outdir = os.path.dirname(outfile)
    ctat_dir = os.path.join(ctat_outdir, "ctat_out")
    tar_out = os.path.join(ctat_outdir, "{}.ctat-LR-fusion.tar.gz".format(sample))
    resource_dir = PARAMS.get("fusion_ctat_resource_dir", "")
    if not resource_dir or not os.path.isdir(resource_dir):
        raise ValueError(
            "fusion_ctat_resource_dir must point to a ctat-LR-fusion "
            "genome_lib_dir: {}".format(resource_dir)
        )

    run_prefix = PARAMS.get(
        "fusion_run_prefix",
        "singularity exec --bind $PWD /path/to/ctat_lr_fusion.sif",
    )
    threads = max(2, PARAMS.get("fusion_threads", 8) - 2)
    job_memory = PARAMS.get("fusion_memory", "16G")
    fusion_preds = os.path.join(ctat_dir, "ctat-LR-fusion.fusion_predictions.tsv")

    statement = """
        rm -rf %(ctat_dir)s
        && mkdir -p %(ctat_dir)s
        && %(run_prefix)s ctat-LR-fusion
        --LR_bam %(infile)s
        --genome_lib_dir %(resource_dir)s
        --CPU %(threads)s
        --vis
        --output %(ctat_dir)s
        && if [ ! -f %(fusion_preds)s ]; then
            touch %(fusion_preds)s;
           fi
        && cp %(fusion_preds)s %(outfile)s
        && tar -czf %(tar_out)s -C %(ctat_outdir)s ctat_out
    """

    P.run(statement)


@transform(find_fusions,
           regex(r"fusions/(\S+)/ctat-LR-fusion\.fusion_predictions\.tsv"),
           r"fusions/\1.ctat-LR-fusion.fusion_predictions_per-read.tsv")
def format_fusions(infile, outfile):
    """
    Join ctat-LR-fusion predictions to cell barcodes from the tagged BAM.

    Writes per-read and per-fusion summary tables (wf ``format_ctat_output``).
    """
    if not PARAMS.get("fusion_call_fusions", False):
        raise ValueError("fusion_call_fusions is false.")

    PYTHON_SRC_PATH = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "python"))

    sample = infile.split("/")[1]
    tagged_bam = "tagged/{}.tagged.bam".format(sample)
    out_fusion = outfile.replace("_per-read.tsv", "_per-fusion.tsv")
    job_memory = PARAMS.get("fusion_memory", "4G")

    statement = """
        python %(PYTHON_SRC_PATH)s/ctat_fusion_format.py
        --predictions %(infile)s
        --bam %(tagged_bam)s
        --sample %(sample)s
        --out-read %(outfile)s
        --out-fusion %(out_fusion)s
    """

    P.run(statement)


# -----------------------------------------------
# Targeted translocation scanning (split-mm port, single-cell)
# -----------------------------------------------

@follows(mkdir("targeted_fusions"))
@transform(subset_cells,
           regex(r"tagged_cells/(\S+)\.cells\.bam"),
           r"targeted_fusions/\1.targeted_fusion.per_cell.tsv")
def targeted_fusion_scan(infile, outfile):
    """
    Scan barcode-tagged BAM for reads supporting whitelist translocation pairs.

    Uses genomic window pairs (exact + padded broad windows) and aggregates
    supporting reads and UMIs per cell barcode. Writes per-target summary,
    per-cell long table, cell x translocation matrices, and per-read evidence.

    Requires targeted_fusion_run: true in pipeline.yml.
    """
    if not PARAMS.get("targeted_fusion_run", False):
        raise ValueError(
            "targeted_fusion_run is false. Set targeted_fusion.run: true "
            "in pipeline.yml and run ``make targeted_fusions``."
        )

    sample = os.path.basename(infile).replace(".cells.bam", "")
    whitelist = PARAMS.get("targeted_fusion_whitelist", "")
    if not whitelist or not os.path.isfile(whitelist):
        raise ValueError(
            "targeted_fusion_whitelist must point to an existing TSV file: "
            "{}".format(whitelist)
        )

    bam_source = PARAMS.get("targeted_fusion_bam_source", "cells")
    if bam_source == "all":
        bam = "tagged/{}.tagged.bam".format(sample)
    else:
        bam = infile

    if not os.path.isfile(bam):
        raise ValueError("BAM not found for targeted fusion scan: {}".format(bam))

    outdir = os.path.dirname(outfile) or "targeted_fusions"
    job_memory = PARAMS.get("targeted_fusion_memory", "8G")
    window_size = PARAMS.get("targeted_fusion_window_size", 1000000)
    padding_units = PARAMS.get("targeted_fusion_padding_units", "windows")
    min_mapq = PARAMS.get("targeted_fusion_min_mapq", 20)
    matrix_window = PARAMS.get("targeted_fusion_matrix_window", "exact")
    keep_secondary = PARAMS.get("targeted_fusion_keep_secondary", False)

    PYTHON_SRC_PATH = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "python"))

    keep_secondary_flag = " --keep-secondary" if keep_secondary else ""

    statement = """
        python %(PYTHON_SRC_PATH)s/sc_fusion_windows.py
        --bam %(bam)s
        --whitelist %(whitelist)s
        --sample %(sample)s
        --outdir %(outdir)s
        --out-prefix %(sample)s
        --window-size %(window_size)s
        --padding-units %(padding_units)s
        --min-mapq %(min_mapq)s
        --matrix-window %(matrix_window)s
        %(keep_secondary_flag)s
    """

    P.run(statement)


# -----------------------------------------------
# Per-cell SNV calling (longshot, wf-single-cell port)
# -----------------------------------------------

@follows(mkdir("snv"))
@transform(PARAMS["genome_fasta"],
           regex(r"(.*)"),
           r"snv/ref.dict")
def snv_genome_prep(infile, outfile):
    """
    Index reference FASTA and build GATK sequence dictionary for SNV calling.
    """
    if not PARAMS.get("snv_call_variants", False):
        with open(outfile, "w") as fh:
            fh.write("skipped\n")
        return

    ref_link = os.path.join(os.path.dirname(outfile), "ref.fa")
    job_memory = PARAMS.get("snv_memory", "4G")

    statement = """
        ln -sf $(realpath %(infile)s) %(ref_link)s
        && samtools faidx %(ref_link)s
        && gatk CreateSequenceDictionary --REFERENCE %(ref_link)s --OUTPUT %(outfile)s
    """

    P.run(statement)


@follows(snv_genome_prep)
@transform(subset_cells,
           regex(r"tagged_cells/(\S+)\.cells\.bam"),
           r"snv/\1/per_cell_bams/.sentinel")
def snv_split_cells(infile, outfile):
    """
    Split cell-subset BAM by CB tag (``samtools split -d CB``).
    """
    if not PARAMS.get("snv_call_variants", False):
        open(outfile, "w").write("skipped\n")
        return

    sample_dir = os.path.dirname(outfile)
    per_cell = os.path.join(sample_dir, "per_cell_bams")
    job_threads = PARAMS.get("snv_threads", 8)
    job_memory = PARAMS.get("snv_memory", "32G")

    statement = """
        ulimit -n 20000
        && rm -rf %(per_cell)s
        && mkdir -p %(per_cell)s
        && samtools split --max-split 20000
        -d CB
        --threads %(job_threads)s
        -f '%(per_cell)s/%%!.bam'
        --no-PG
        %(infile)s
        && samtools index -@ %(job_threads)s -M %(per_cell)s/*.bam
        && touch %(outfile)s
    """

    P.run(statement)


@transform(snv_split_cells,
           regex(r"snv/(\S+)/per_cell_bams/\.sentinel"),
           r"snv/\1/call1.sentinel")
def snv_call1(infile, outfile):
    """Round-1 per-cell longshot (dedup, SplitNCigarReads, discovery)."""
    if not PARAMS.get("snv_call_variants", False):
        open(outfile, "w").write("skipped\n")
        return

    PYTHON_SRC_PATH = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "python"))
    sample_dir = os.path.dirname(os.path.dirname(infile))
    ref_fa = "snv/ref.fa"
    job_threads = PARAMS.get("snv_threads", 8)
    job_memory = PARAMS.get("snv_memory", "32G")
    snv_call1_min_alt_count = PARAMS.get("snv_call1_min_alt_count", 1)
    snv_call1_min_cov = PARAMS.get("snv_call1_min_cov", 1)

    statement = """
        python %(PYTHON_SRC_PATH)s/longshot_sc.py call1
        --sample-dir %(sample_dir)s
        --ref %(ref_fa)s
        --threads %(job_threads)s
        --min-alt-count %(snv_call1_min_alt_count)s
        --min-cov %(snv_call1_min_cov)s
        && touch %(outfile)s
    """

    P.run(statement)


@transform(snv_call1,
           regex(r"snv/(\S+)/call1\.sentinel"),
           r"snv/\1/bulk_merged.vcf.gz")
def snv_bulk(infile, outfile):
    """Bulk longshot on merged exon-split BAMs (per contig)."""
    if not PARAMS.get("snv_call_variants", False):
        open(outfile, "w").write("skipped\n")
        return

    PYTHON_SRC_PATH = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "python"))
    sample_dir = os.path.dirname(infile)
    ref_fa = "snv/ref.fa"
    job_memory = PARAMS.get("snv_memory", "32G")
    snv_bulk_min_alt_count = PARAMS.get("snv_bulk_min_alt_count", 2)
    snv_bulk_min_cov = PARAMS.get("snv_bulk_min_cov", 2)

    statement = """
        python %(PYTHON_SRC_PATH)s/longshot_sc.py bulk
        --sample-dir %(sample_dir)s
        --ref %(ref_fa)s
        --min-alt-count %(snv_bulk_min_alt_count)s
        --min-cov %(snv_bulk_min_cov)s
    """

    P.run(statement)


@transform(snv_bulk,
           regex(r"snv/(\S+)/bulk_merged\.vcf\.gz"),
           r"snv/\1/candidates.vcf.gz")
def snv_merge_candidates(infile, outfile):
    """Merge bulk + round-1 cell VCFs into candidate sites."""
    if not PARAMS.get("snv_call_variants", False):
        open(outfile, "w").write("skipped\n")
        return

    PYTHON_SRC_PATH = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "python"))
    sample_dir = os.path.dirname(infile)
    merge_threads = PARAMS.get("snv_merge_threads", 8)
    job_memory = PARAMS.get("snv_memory", "16G")

    statement = """
        python %(PYTHON_SRC_PATH)s/longshot_sc.py merge_candidates
        --sample-dir %(sample_dir)s
        --merge-threads %(merge_threads)s
    """

    P.run(statement)


@transform(snv_merge_candidates,
           regex(r"snv/(\S+)/candidates\.vcf\.gz"),
           r"snv/\1/genotype2.sentinel")
def snv_genotype2(infile, outfile):
    """Round-2 per-cell genotyping at merged candidate sites."""
    if not PARAMS.get("snv_call_variants", False):
        open(outfile, "w").write("skipped\n")
        return

    PYTHON_SRC_PATH = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "python"))
    sample_dir = os.path.dirname(infile)
    ref_fa = "snv/ref.fa"
    ref_fai = "snv/ref.fa.fai"
    job_threads = PARAMS.get("snv_threads", 8)
    job_memory = PARAMS.get("snv_memory", "32G")
    snv_depth_target = PARAMS.get("snv_depth_target", 200)
    snv_genotype2_min_alt_count = PARAMS.get("snv_genotype2_min_alt_count", 1)
    snv_genotype2_min_cov = PARAMS.get("snv_genotype2_min_cov", 1)

    statement = """
        python %(PYTHON_SRC_PATH)s/longshot_sc.py genotype2
        --sample-dir %(sample_dir)s
        --ref %(ref_fa)s
        --ref-fai %(ref_fai)s
        --threads %(job_threads)s
        --depth-target %(snv_depth_target)s
        --min-alt-count %(snv_genotype2_min_alt_count)s
        --min-cov %(snv_genotype2_min_cov)s
        && touch %(outfile)s
    """

    P.run(statement)


@transform(snv_genotype2,
           regex(r"snv/(\S+)/genotype2\.sentinel"),
           r"snv/\1/\1.final_merged.vcf.gz")
def snv_merge_matrix(infile, outfile):
    """
    Merge round-2 cell VCFs and build sparse genotype MEX matrix.

    Outputs ``snv/{sample}/{sample}.final_merged.vcf.gz`` and
    ``snv/{sample}/{sample}.genotype_matrix/`` (0=hom ref, 1=het, 2=hom alt).
    """
    if not PARAMS.get("snv_call_variants", False):
        open(outfile, "w").write("skipped\n")
        return

    PYTHON_SRC_PATH = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "python"))
    sample = os.path.basename(os.path.dirname(infile))
    sample_dir = os.path.dirname(infile)
    merge_threads = PARAMS.get("snv_merge_threads", 8)
    report_variants = PARAMS.get("snv_report_variants", "")
    rv_flag = "--report-variants {}".format(report_variants) if report_variants else ""
    job_memory = PARAMS.get("snv_memory", "32G")

    statement = """
        python %(PYTHON_SRC_PATH)s/longshot_sc.py merge_matrix
        --sample-dir %(sample_dir)s
        --sample %(sample)s
        --merge-threads %(merge_threads)s
        %(rv_flag)s
    """

    P.run(statement)


# -----------------------------------------------
# QC: NanoPlot
# -----------------------------------------------

@follows(mkdir("qc_nanoplot"))
@transform(align_minimap2,
           regex(r"aligned/(\S+)\.bam"),
           r"qc_nanoplot/\1/NanoStats.txt")
def qc_nanoplot(infile, outfile):
    """
    Run NanoPlot on aligned BAM files for long-read QC metrics.

    Large nuclei BAMs often OOM NanoPlot's process pool (BrokenProcessPool /
    signal -1). Defaults enable --huge and request more memory; lower
    nanoplot.threads or set nanoplot.downsample if it still fails.
    """

    outdir = os.path.dirname(outfile)

    job_threads = PARAMS.get("nanoplot_threads", 2)
    job_memory = PARAMS.get("nanoplot_memory", "32G")
    huge = PARAMS.get("nanoplot_huge", True)
    downsample = PARAMS.get("nanoplot_downsample", None)
    extra = PARAMS.get("nanoplot_options", "")

    huge_opt = "--huge" if huge else ""
    downsample_opt = ""
    if downsample:
        downsample_opt = "--downsample %s" % downsample

    statement = """
        NanoPlot --bam %(infile)s
        -o %(outdir)s
        --tsv_stats
        --plots dot
        -t %(job_threads)s
        %(huge_opt)s
        %(downsample_opt)s
        %(extra)s
    """

    P.run(statement)


# -----------------------------------------------
# QC: Cell barcode statistics
# -----------------------------------------------

@follows(mkdir("qc_cells"))
@merge(run_blaze, "qc_cells/barcode_summary.txt")
def summarize_barcodes(infiles, outfile):
    """
    Summarize cell barcode assignment statistics across all samples.
    """

    import pandas as pd

    dfs = []
    for infile in infiles:
        sample = os.path.basename(infile).replace("_barcode_stats.txt", "")
        df = pd.read_csv(infile, sep="\t")
        df["sample"] = sample
        dfs.append(df)

    combined = pd.concat(dfs, ignore_index=True)
    combined.to_csv(outfile, sep="\t", index=False)


# -----------------------------------------------
# MultiQC: Aggregate reports
# -----------------------------------------------

@follows(qc_nanoplot, count_genes, summarize_barcodes, qc_splice_proportion)
@merge([align_minimap2, "qc_nanoplot/*", "genecounts/*", "qc_splice/*"],
       "multiqc/multiqc_report.html")
def multiqc(infiles, outfile):
    """
    Aggregate all QC reports using MultiQC.
    """

    outdir = os.path.dirname(outfile)

    statement = """
        export LC_ALL=en_US.UTF-8 &&
        export LANG=en_US.UTF-8 &&
        multiqc -f -n multiqc_report.html -o %(outdir)s .
    """

    P.run(statement)


# -----------------------------------------------
# Pipeline targets
# -----------------------------------------------

@follows(count_genes, count_velocity, multiqc,
         quantify_isoquant, build_splice_matrices, qc_splice_proportion,
         generate_isoquant_report)
def full():
    """
    Run the complete pipeline: alignment, IsoQuant discovery/quantification,
    gene counts, velocity matrices, and QC.

    IsoQuant (from tagged BAM) is the default transcript discovery route and
    scales better to high cell counts. FLAMES is opt-in via ``make flames``
    for smaller samples (set flames.run: true).
    """
    pass


@follows(align_minimap2, run_blaze, tag_bam_with_barcodes)
def align():
    """
    Run alignment and barcode tagging only.
    """
    pass


@follows(run_flames)
def flames():
    """
    Opt-in FLAMES transcript analysis from FASTQ (set flames.run: true).

    Prefer for smaller samples; use IsoQuant (``make full`` / ``make quantify``)
    for high cell-count libraries.
    """
    pass


@follows(count_genes, count_velocity,
         quantify_isoquant, build_splice_matrices, qc_splice_proportion)
def quantify():
    """
    Run quantification only (requires aligned BAMs upstream).

    IsoQuant from the tagged BAM (UMI-deduplicated spliced/unspliced matrices
    and isoform discovery), plus featureCounts gene counts and velocity
    matrices. FLAMES is not included; use ``make flames`` separately.
    """
    pass


@follows(qc_nanoplot, summarize_barcodes, multiqc, generate_isoquant_report)
def qc():
    """
    Run QC only, including IsoQuant static HTML report generation.
    """
    pass


@follows(generate_isoquant_report)
def isoquant_report():
    """
    Generate IsoQuant QC HTML reports only (requires splice matrices upstream).
    """
    pass


@follows(format_fusions)
def fusions():
    """
    Run ctat-LR-fusion fusion calling on tagged BAMs.

    Requires fusion.call_fusions: true in pipeline.yml.
    """
    pass


@follows(targeted_fusion_scan)
def targeted_fusions():
    """
    Scan tagged BAMs for whitelist translocation pairs per cell.

    Requires targeted_fusion.run: true in pipeline.yml.
    """
    pass


@follows(snv_merge_matrix)
def variants():
    """
    Run per-cell longshot SNV calling and build genotype matrix.

    Requires snv.call_variants: true in pipeline.yml. Computationally
    intensive (~24h/64 cores for ~1500 cells per wf-single-cell).
    """
    pass


def main(argv=None):
    if argv is None:
        argv = sys.argv
    P.main(argv)


if __name__ == "__main__":
    sys.exit(P.main(sys.argv))
