# Pipeline configuration file for pipeline_ontqc.py

# General pipeline options
pipeline_name: pipeline_ontqc

# NanoPlot parameters
nanoplot:
    # Number of threads to use
    threads: 4
    
    # Read length filtering
    maxlength: 100000
    minlength: 1000
    
    # Additional options (can be overridden in command line)
    options: --plots kde hex dot --N50 --raw --store

# LongQC parameters
longqc:
    # Preset for the sequencing platform/kit
    # Options: pb-rs2, pb-sequel, ont-ligation, ont-rapid, ont-1dsq
    preset: ont-ligation
    
    # Number of threads
    threads: 4
    
    # Memory limit in GB
    memory: 0.5
    
    # Additional options
    options: --fast
