################################################################
#
# Pipeline pipeline_trna.py configuration file
#
# This pipeline.yml file lists some configuration options that you
# need to set before running the pipeline. 
#
################################################################

# Location of the cribbslab directory
cribbslab: '/ifs/devel/annajb/tRNA_mapping/cribbslab/'

# Project name
projectname: proj001

# Copyright statement
copyright: Cribbs Group, Botnar Research Centre (2018)

##########################################################
# UCSC database options
##########################################################

ucsc:
# UCSC database host
    host: genome-mysql.cse.ucsc.edu

# UCSC database user name
    user: genome

# UCSC database name
    database: hg19

# repeats to collect as ',' separated list
    repeattypes: DNA,LINE,SINE,LTR,Transposon

# RNA repeats to collect as ',' separated list
    rnatypes: RNA,rRNA,scRNA,snRNA,srpRNA,tRNA

# comma separated list of regular expressions (a word contained in the contig that defines the contigs to be removed) 
# for contigs (ensembl nomenclature)
# to be removed from ensembl_filename_gtf during genome
# sanitization
    remove_contigs: random,chrUn,na,alt


########################################################
# the genome to use (UCSC convention)
########################################################

genome: hg19
# The folder that the genome is located in
genome_dir: /ifs/mirror/genomes/index/

##########################################################
# location of a bowtie2 indexed genome
# for infomation on how to build this please refer to: http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml#getting-started-with-bowtie-2-lambda-phage-example
##########################################################

bowtie:
    genome : hg19
    genome_dir: /ifs/mirror/genomes/bowtie/
    options: --local --very-sensitive-local

###########################################################
# tRNA scan options
# Run trna scan if 1, otherwise include location of indexed genome.
############################################################
index:

# Run tRNA scan
    run : 0

# Location of pre-indexed genome 
    genome_dir : /ifs/research-groups/botnar/proj025/analyses/
    genome : tRNAscan_h38

trna_scan: 
    # Option to load pre-downloaded genomic tRNA scan annotations from http://gtrnadb.ucsc.edu/index.html
    load: 0

    path : /ifs/research-groups/botnar/proj025/analyses/test_april/
  
    folder : hg38-tRNAs
    # no tar.gz needed

######

